### ISSUE TITLE
Construction Differences Between Small Office Building in ClimateZone 2A, ASHRAE 90.1-2010

### ISSUE THREAD

**Issue by jonathankocher** [NREL/openstudio-standards#102]
I notice differences in the floor, roof and wall constructions between the EnergyPlus and OpenStudio Prototype Small Office Building for ASHRAE 90.1-2010, ClimateZone 2A. See excel attachment for differences. 

Also, I am new to GitHub and have been unable to find any forum standards, so my apologies if this issue is not formatted correctly. 
[OpenStudio.EnergyPlus.Construction.Differences.Small.Office.Building.-.Climate.Zone.2A.-.ASHRAE.90.1-2010.xlsx](https://github.com/NREL/openstudio-standards/files/392661/OpenStudio.EnergyPlus.Construction.Differences.Small.Office.Building.-.Climate.Zone.2A.-.ASHRAE.90.1-2010.xlsx)

**Comment by asparke2** [comment]
Thanks for reporting this, we'll check it out!

**Comment by lymereJ** [comment]
Floor constructions have been updated to use the F-factor modeling approach, the modeled thermal performance of walls and roofs are now aligned.
