### ISSUE TITLE
Lighting radiant fractions

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#1050]
Currently, lighting in openstudio-standards generated models have a radiant fraction of 0.7, specified in the 'Lighting Fraction Radiant' field in the openstudio-standards spreadsheet.  This value appears to come from Table 1.23 in the EnergyPlus Input/Output Reference, Fixture # 5 for "Recessed,Direct/Indirect, T8 -Half Typical Supply Airflow Rate", summing the return air fraction (0.43) and radiant fraction (0.27).

These values originally came from ASHRAE RP-1282 “Lighting Heat Gain Distribution in Buildings”

LED lighting is now commonplace in codes, and there is a need to update the radiant fractions to reflect that.  See ASHRAE RP-1681 -- "Low Energy LED Lighting Heat Distribution in Buildings"

Furthermore, openstudio-standards differentiates between different kinds of lighting (Linear, Compact, High Bay, Specialty, Exit), which all have different fractions in a specific space type.  We'd like to accurately capture the radiant fractions for these kinds of lighting, as it will matter in terms of how much load is delayed.

Options for this are:
1) Weight the radiant fractions by installed power
2) Assign a different radiant fraction for each kind of lighting, dependent on vintage

We may want a broader stock turnover that explicitly calls out other style of lighting and add additional lighting types to ComStock.

**Comment by mpraprost** [comment]
Style | Existing Luminaire Assumptions | Existing Fraction | New Luminaire Assumptions   (Pre-2016 Vintages) | New Fraction (Pre-2016 Vintages) | New Luminaire Assumptions (2016+   Vintages) | New Fraction (2016+ Vintages)
-- | -- | -- | -- | -- | -- | --
Linear   Fluorescent | T12s, T8s, T5s | 0.7 | T12s, T8s, T5s | 0.7 | Recessed LED Troffer Uniform   Diffuser | 0.38
Compact   Fluorescent | CFLs | 0.7 | Downlight CFLs | 0.14 | Recessed LED downlight | 0.15
High Bay | HIDs | 0.7 | HIDs | Cant find anything | High bay LED | 0.46
Specialty | Pendant, Accent | 0.7 | Pendants/Halogen | 0.55 | linear pendant LED | 0.57
Exit | Exit | 0.7 | Exit | 0.55 | Exit | 0.57

**Comment by mpraprost** [comment]
Hi @jiangithub - any thoughts from PNNL about these proposed changes to lighting radiant fractions?
