### ISSUE TITLE
Toilet exhaust fans as miscellaneous loads

### ISSUE THREAD

**Issue by agonzalezesteve** [NREL/openstudio-standards#1074]
When creating the baseline building the efficiency of exhaust fans is changed compared to the proposed one.

https://github.com/NREL/openstudio-standards/blob/99cf713750661fe7d2082739f251269c2dfd9140/lib/openstudio-standards/standards/Standards.Model.rb#L1505

We consider exhaust fans as miscellaneous loads so they shall be identical in the proposed and the baseline buildings.

How we should consider it?

**Comment by mdahlhausen** [comment]
@agonzalezesteve
This depends on the type of exhaust fan and the zone it is serving.  [See here for guidance](https://www.ashrae.org/File%20Library/Technical%20Resources/Standards%20and%20Guidelines/Standards%20Intepretations/IC_90-1-2004-34.pdf).

openstudio-standards does not distinguish between types of exhaust fans beyond having some logic for small hp fans.  This may change in a new release of the 90.1-2016 appendix G implementation, which may ask for more data about the exhaust fans in the model.

If you think your exhaust fan should be considered a process load, you'll need to updated it manually in the baseline model to match the proposed..
