### ISSUE TITLE
Large office shorter than multiplier would suggest

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#108]
Seems the multiplier is fine, but the mid and top floor is just positioned lower than it should be. Minor issue, but would be nice to fix at some point.
https://unmethours.com/question/18033/why-is-large-office-prototype-building-so-short/

**Comment by DavidGoldwasser** [comment]
Here is geometry for the large_office_reference.osm

![screenshot 2016-11-02 11 54 34](https://cloud.githubusercontent.com/assets/4857055/19941092/6b434aa2-a0f4-11e6-9390-bb32533b4fea.png)

large_office.osm and large_office_2010.osm seem to share the same geometry at first glance (at least height profiles for different spaces).

![screenshot 2016-11-02 12 00 13](https://cloud.githubusercontent.com/assets/4857055/19941139/952703e0-a0f4-11e6-8664-05ee27eea065.png)

@asparke2 I can fix the mid and top floor positions to match large_office.osm without any problem. I did notice the basement height varies as well, I assume that was an intentional decision in support of the data center or for other reasons?. Charnged form 2.2394m to 2.4390m

**Comment by asparke2** [comment]
Yeah it was probably for the data center addition

**Comment by DavidGoldwasser** [comment]
Here is fixed geometry

![screenshot 2016-11-02 12 23 24](https://cloud.githubusercontent.com/assets/4857055/19941899/7fdc173e-a0f7-11e6-91bd-99b76c958b5a.png)
