### ISSUE TITLE
Propane fuel not handled correctly

### ISSUE THREAD

**Issue by shorowit** [NREL/openstudio-standards#1100]
OS-standards is still requiring the older convention of 'PropaneGas' for propane fuel. When e.g. a [boiler is created](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/common/objects/Prototype.BoilerHotWater.rb#L47-L51), it uses this string directly which is incompatible with the OS/E+ IDD, so the boiler incorrectly ends up with natural gas fuel (the default).

Two possibilities:
1. Continue to require 'PropaneGas', but convert it to 'Propane' as needed for E+.
2. Change all instances in the code from 'PropaneGas' to 'Propane'.

**Comment by mdahlhausen** [comment]
Addressed with #1292.
