### ISSUE TITLE
Add constant schedule ruleset value tolerance

### ISSUE THREAD

**Issue by agonzalezesteve** [NREL/openstudio-standards#1119]
`model_add_constant_schedule_ruleset` method should have a tolerance with value because when having a temperature with periodic value, for example OpenStudio.convert(180, "F", "C").get, adds lots of schedules.

https://github.com/NREL/openstudio-standards/blob/c855838717a078e877789a7206865cbb311548fa/lib/openstudio-standards/standards/Standards.Model.rb#L1952

For example using `(existing_day_sch_vals[0] - value).abs < 1e-6` instead of `existing_day_sch_vals[0] == value`

**Comment by mdahlhausen** [comment]
fixed with #1304
