### ISSUE TITLE
out_temp_lmt variable in create_boiler_hot_water method

### ISSUE THREAD

**Issue by agonzalezesteve** [NREL/openstudio-standards#1121]
First of all, `create_boiler_hot_water` is called here
https://github.com/NREL/openstudio-standards/blob/c855838717a078e877789a7206865cbb311548fa/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb#L144
and here
https://github.com/NREL/openstudio-standards/blob/c855838717a078e877789a7206865cbb311548fa/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb#L801
with `out_temp_lmt` in degrees Celsius. But method
https://github.com/NREL/openstudio-standards/blob/c855838717a078e877789a7206865cbb311548fa/lib/openstudio-standards/prototypes/common/objects/Prototype.BoilerHotWater.rb#L20
reads it in Fahrenheit.

In addition, `out_temp_lmt` has `203.0 F` as default value, so it's never `nil` and it's always overwritten by
https://github.com/NREL/openstudio-standards/blob/c855838717a078e877789a7206865cbb311548fa/lib/openstudio-standards/prototypes/common/objects/Prototype.BoilerHotWater.rb#L79

**Comment by mdahlhausen** [comment]
Addressed with #1293
