### ISSUE TITLE
std.model_remove_prm_hvac does not remove AirLoopHVAC:DedicatedOutdoorAirSystems

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#1226]
`AirLoopHVAC:DedicatedOutdoorAirSystem`s are not AirLoopHVACs (or zone equipment), so are not removed by `std.model_remove_prm_hvac`. Thus they remain in the baseline model and cause problems with the EnergyPlus run because they have no AirLoopHVAC names set.

I suppose this could be dealt with by OpenStudio (i.e. don't translate AirLoopHVAC:DOAS with no AirLoopHVACs assigned), but I figured it's worth a note here, too.

**Comment by mdahlhausen** [comment]
Fixed with #1291
