### ISSUE TITLE
zone_equipment_heating/cooling_fuels should check AirLoopHVACUnitarySystems

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#1228]
AirLoopHVACUnitarySystems can be zone equipment, but are not checked in `zone_equipment_heating_fuels` or `zone_equipment_cooling_fuels`:

https://github.com/NREL/openstudio-standards/blob/54ca8375f288cacc471d4e9d82b1c8d4009b2fb3/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb#L259

https://github.com/NREL/openstudio-standards/blob/54ca8375f288cacc471d4e9d82b1c8d4009b2fb3/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb#L347

**Comment by eringold** [comment]
https://github.com/NREL/openstudio-standards/pull/1244

**Comment by eringold** [comment]
typo here: https://github.com/NREL/openstudio-standards/blob/abae01541a336d08f736eb00fad9fba24fea4f23/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb#L266

should be `when OS_AirLoopHVAC_UnitarySystem`

**Comment by mdahlhausen** [comment]
Fixed with #1418
