### ISSUE TITLE
Skylight SHGC and U-values Appear Incorrect for ASHRAE 90.1 2016 and 2019

### ISSUE THREAD

**Issue by chriswmackey** [NREL/openstudio-standards#1252]
I'll admit that I am not 100% sure if this is a bug or if there's some exception to the rule within ASHARE 90.1 that I am missing but, at the least, I can say that the 2019 properties for skylights in [the great Google Sheet](https://docs.google.com/spreadsheets/d/1MYQGPd3WFaaSHGnwcmYoNi7TLDgE76LjecTEkY0vGco/edit?usp=sharing) do not appear to be aligned with Table 5.5 in ASHRAE 90.1 2019.

Here is one example that I found in the Google sheet where the skylight has a U of 0.75 and SHGC of 0.55:
![image](https://user-images.githubusercontent.com/5567574/148310381-9837173a-7638-4571-9e1f-c56f98118eaf.png)

Table 5.5 of ASHRAE 90.1 2019 says that the max U for this case is 0.7 and the max SHGC is 0.3:
![image](https://user-images.githubusercontent.com/5567574/148310497-4d295b1b-6156-4314-bad6-f0b258611460.png)

I haven't gotten the chance to verify all of the skylight properties across all climate zones but the user who brought this to my attention said the following: "skylight SHGC values for both 2016 and 2019 are incorrect, as are skylight U-factors in climate zones 1 and 6-8 for ASHRAE 90.1-2019." More information of this user report can be found [here on the Ladybug Tools forum](https://discourse.ladybug.tools/t/default-ashrae-90-1-envelope-parameters-additional-options/16435/6?u=chris).

**Comment by lymereJ** [comment]
@chriswmackey - Thank you for reporting the issue!

Short answer, yes, this is a mistake, we'll create PR for it. 

Long answer, new `Standards Construction Type` were introduced for 90.1-2016/9 that are specific to the DOE prototypes model which takes into account the fact that multiple fenestration type are used in each model, you'll find them under "weighted" in the Google Sheet. Non-weighted requirements were also updated but it looks like skylights have been missed.

**Comment by chriswmackey** [comment]
Thanks for the explanation, @lymereJ . It makes sense. I will await the PR and check back here for any updates.

**Comment by mdahlhausen** [comment]
Addressed with #1253
