### ISSUE TITLE
Curves with missing independent variable min/max limits create unrealistic curves and equipment performance

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#1258]
When the min/max independent variable inputs are not included in curve data, the generated curves default to values of 0 (min) and 1 (max). When the independent variables represent, e.g. temperature values (as in Chiller biquadratic curves where the independent variables are leaving CHW/entering condenser temperatures), the default limits produce curve output that significantly affects model result. 

For example, a DEER small office prototype building with a water-cooled chiller uses [this](https://github.com/NREL/openstudio-standards/blob/6f11187525b505519bbe8521cf3998facbc01768/lib/openstudio-standards/standards/deer/data/deer.curves.json#L12354-L12376) data to build the Cap-fCHWT&ECT curve, which end up like: 
```
Curve:Biquadratic,
  ScrewH2O-Cap-fCHWT&ECT,                 !- Name
  1.07096667,                             !- Coefficient1 Constant
  0.02693502,                             !- Coefficient2 x
  0.000768,                               !- Coefficient3 x**2
  -0.00643302,                            !- Coefficient4 y
  -9.49e-05,                              !- Coefficient5 y**2
  -6.59e-05,                              !- Coefficient6 x*y
  0,                                      !- Minimum Value of x {BasedOnField A2}
  1,                                      !- Maximum Value of x {BasedOnField A2}
  0,                                      !- Minimum Value of y {BasedOnField A3}
  1;                                      !- Maximum Value of y {BasedOnField A3}
```
Running the same model, but setting the curve limits (for the Cap and EIR-fTemp curves) to more realistic values:
```
Curve:Biquadratic,
  ScrewH2O-Cap-fCHWT&ECT,                 !- Name
  1.07096667,                             !- Coefficient1 Constant
  0.02693502,                             !- Coefficient2 x
  0.000768,                               !- Coefficient3 x**2
  -0.00643302,                            !- Coefficient4 y
  -9.49e-05,                              !- Coefficient5 y**2
  -6.59e-05,                              !- Coefficient6 x*y
  4.44,                                   !- Minimum Value of x {BasedOnField A2}
  12.22,                                  !- Maximum Value of x {BasedOnField A2}
  23.89,                                  !- Minimum Value of y {BasedOnField A3}
  46.11;                                  !- Maximum Value of y {BasedOnField A3}
```
results in an almost 30% increase in annual cooling energy!
Obviously there is a challenge of what 'good' values are for the various curve data sources, but perhaps some judgement can be exercised (and documented) so that obviously bad input isn't used?

@mdahlhausen @asparke2 thoughts?

**Comment by mdahlhausen** [comment]
Curves are on our list of things to work on.  I didn't realize how bad it is that the DEER curves are missing limits.
While EnergyPlus will give a warning if the values go into the extrapolated region of the curve, in reality few people ever check the .err file to check and correct for that warning message.

Thanks for pointing this out.

Seems like the appropriate course of action here is to go through the list of curves and fill in the limits where temperature is one of the independent variables.

**Comment by eringold** [comment]
Thanks @mdahlhausen!
FYI, it's not just the DEER dataset that's missing curve min/max values. The following are all the BiQuadratic curves with `independent_variable_1 == "CHWT"` and `minimum_independent_variable_1 == nil` in ashrae_90_1.curves.json, cbes.curves.json and deer.curves.json: 
```
   "CentChlrAirCoolCap-fCHW&OAT",
   "CentChlrAirCoolEIR-fCHW&OAT",
   "CentH2O-Cap-fCHWT&ECT",
   "CentH2O-EIR-fCHWT&ECT",
   "CentH2OVSD-Cap-fCHWT&ECT",
   "CentH2OVSD-EIR-fCHWT&ECT",
   "ChlrHPAirCoolCap-fCHW&OAT",
   "ChlrHPAirCoolEIR-fCHW&OAT",
   "ChlrHPH2OCoolCap_fCHW&ECT",
   "ChlrHPH2OCoolCap_fCHW&ECT-Old",
   "ChlrHPH2OCoolEIR_fCHW&ECT",
   "ChlrHPH2OCoolEIR_fCHW&ECT-Old",
   "Lp2Lp_Cap_fCHW&HWR",
   "Lp2Lp_EIR_fCHW&HWR",
   "RecipAir-Cap-fCHWT&DBT",
   "RecipAir-EIR-fCHWT&DBT",
   "RecipH2O-Cap-fCHWT&ECT",
   "RecipH2O-EIR-fCHWT&ECT",
   "RecipRemote-Cap-fCHWT&SCT",
   "RecipRemote-EIR-fCHWT&SCT",
   "ScrewAir-Cap-fCHWT&DBT",
   "ScrewAir-EIR-fCHWT&DBT",
   "ScrewH2O-Cap-fCHWT&ECT",
   "ScrewH2O-EIR-fCHWT&ECT",
   "ScrewRemote-Cap-fCHWT&SCT",
   "ScrewRemote-EIR-fCHWT&SCT",
   "ScrollChlrAirCoolCap-fCHW&OAT",
   "ScrollChlrAirCoolEIR-fCHW&OAT"
```

**Comment by mdahlhausen** [comment]
related to #80
