### ISSUE TITLE
Laboratory prototype missing fume hood exhaust fans

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#1278]
Marked as todo and stubbed out here:
https://github.com/NREL/openstudio-standards/blob/67b0223d82fd32f8201969159f02a487dcf2f8e2/lib/openstudio-standards/prototypes/common/buildings/Prototype.Laboratory.rb#L41-L46

**Comment by mdahlhausen** [comment]
@KaiyuSun any thoughts on how we should address this?

**Comment by KaiyuSun** [comment]
@eringold Thanks for catching the leftover TODO item! 
@mdahlhausen I'll work on it next week and let you know when I'm finished.

**Comment by KaiyuSun** [comment]
@mdahlhausen Just pushed the updated codes, check it out https://github.com/NREL/openstudio-standards/pull/1287#issue-1174076114

Besides, I found a potential issue with the zone exhaust fan efficiency and posted [here](https://github.com/NREL/openstudio-standards/issues/1286#issue-1174067905), could you help examine as well?

**Comment by mdahlhausen** [comment]
Addressed with #1287, though there is still an issue with the exhaust fan efficiency as detailed in #1286.
