### ISSUE TITLE
Prototype.hvac_systems.rb uses deprecated AirLoopHVAC::availabilityManager method

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#1369]
AirLoopHVAC::availabilityManager has been deprecated and removed from OpenStudio, but is still used in Prototype.hvac_systems.rb: 

model_add_vav_reheat:
https://github.com/NREL/openstudio-standards/blob/971514ee0a64262a9c81788fd85fc60d8dd69980/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb#L1718

model_add_pvav: 
https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb#L2069

model_add_psz_reheat:
https://github.com/NREL/openstudio-standards/blob/971514ee0a64262a9c81788fd85fc60d8dd69980/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb#L2680

**Comment by mdahlhausen** [comment]
Fixed with #1393
