### ISSUE TITLE
Small data center with low ITE fails in climate zone 6 through 8

### ISSUE THREAD

**Issue by lymereJ** [NREL/openstudio-standards#1382]
The small data center with low ITE fails to be generated in climate zone 6 through 8 when using the ASHRAE 169-2013 reference locations. The test currently uses the ASHRAE 169-2006 reference locations and passes. The reason for the failure is that the design day run fails because reportedly a surface from the model reaches really low temperatures. The test was conducted with OpenStudio 3.2.1 and 3.3.0.

**Comment by lymereJ** [comment]
The same issue occurs for the small data center with high ITE.

**Comment by mdahlhausen** [comment]
@KaiyuSun this is a data center prototype issue

**Comment by KaiyuSun** [comment]
Msg received. I'll work on it and keep you posted.
