### ISSUE TITLE
90.1-2016 and 90.1-2019 lighting EMS code

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#1446]
This is issue is already discussed somewhat as issue 1 in #1395.

In OpenStudio v3.3.0 and above, most 90.1-2016 and 90.1-2019 models will fail at runtime with an error like this:
`Invalid Actuated Component Unique Name =CAFETERIA_ZN_1_FLR_1 ZN PRIMARYSCHOOL CAFETERIA LIGHTS  Entered in EnergyManagementSystem:Actuator=CAFETERIA_ZN_1_FLR_1ZN_LIGHT1_ACTUATOR  Component Unique key name not found   Use Output:EnergyManagementSystem object to create .edd file for valid component names.\

It's from the way EMS actuators are translated in the forward translator from OS to E+.  The relevant code is [here](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2016/ashrae_90_1_2016.Model.rb#L261-L367) and [here](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.Model.rb#L261-L368).

Initially, this appeared as an [OpenStudio issue](https://github.com/NREL/OpenStudio/issues/4786).  But as I describe in [this comment](https://github.com/NREL/OpenStudio/issues/4786#issuecomment-1468905643), EnergyPlus is actually right in it's failure, as the code in early versions were actuating the same component.

The issue is that the lights object is defined at the SpaceType level and shared among many spaces / zones.  The EMS control needs to operate on one unique lights object per zone/space.

@lymereJ @weilixu I'll take a shot at addressing this and @ you when I've got it refactored within the next day or so.

**Comment by lymereJ** [comment]
That's sounds okay to me. @leijerry888 developed that EMS. @leijerry888 do you foresee any issue with that approach?
