### ISSUE TITLE
Simplifying default outputs to minimize post processing of data

### ISSUE THREAD

**Issue by boulterr** [NREL/openstudio-standards#145]
I'm trying to use the pre-1980 and 1980-2004 reference buildings along with NECB2011 to generate general, representative hourly energy profiles (heating, cooling, & electric) for Canadian sites, currently working on Ottawa to start for reference.
By default there are several outputs that get generated that I'd like to turn off in an effort to minimize post processing of the hourly data. These include hourly zone temp and humidity as well as any timestep-scale outputs like Site Outdoor Air Drybulb Temp, Electricity: Facility, etc. To help with the issue I had simply changed the number of timesteps from the default 6/hr to 1/hr to at least generate only hourly data vs 10min timestep data for all outputs but I have now discovered that causes undesirable issues with the shape of overall energy profiles. 

Anyway, a task I thought I'd add to the pile that would simplify my life.

For reference, the outputs (all hourly) I'm using for what I need include:
'Heating Coil Air Heating Rate'
'Cooling Coil Total Cooling Rate'
'Boiler Heating Rate'
'Chiller Condenser Heat Transfer Rate'
'Water Heater Heating Rate'
'Facility Total Electric Demand Power'
'Gas:Facility'
'Water Heater Gas Rate'

Phylroy to investigate

**Comment by phylroy** [comment]
Hey Raymond.. What is your current workflow?

1.	Run simulation.
2.	Run ESOVarsRead (or whatever it’s called) 
3.	Get hourly data for the following in a csv file? For only the listed data?

**Comment by boulterr** [comment]
Correct - from which I roll up hourly totals for:
a) SHW demand, 
b) heating demand {sum of heating coils + boiler}, 
c) total heating {a+b}, 
d) cooling demand {sum of cooling coils + chiller condenser}, 
e) facility total electricity, 
f) facility gas, 
g) total site energy {e+f}. 

I then use those rolled up hourly building totals to generate for each:
1. Breakdown of energy by month (kWh & %annual)
2. total weekday and total weekend energy by month and the ratio (Avg weekday energy) / (avg weekend energy)
3. Peak hourly demand and load factor by month 
4. Time percentile load breakdown for load duration curve, also bin distribution of demand relative to peak demand
5. Average weekday and weekend day hourly profile for each month. I have also been generating avg+stdev and avg-stdev hourly to put a boundary on the range of hourly values

**Comment by phylroy** [comment]
BTAPHourly Reports measure has been created to take care of this situation.
