### ISSUE TITLE
How to export json data for OS SDK consumption?

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#1490]
The OS SDK has historically been using two merged JSON files for Materials and Space Types. For the Space Type one, we would take the OpenStudio_Standards_space_types.json + the NCEB data and keep only selected keys we cared about to limit the size of the resulting json. 
The ruby code to generate them and the two current jsons are in https://github.com/NREL/OpenStudio/tree/33626993b6315a614eb67de7b158bf4e5fb384d9/src/model/Resources/standards

This is used as a kind of dependent dropdown to provide suggested standards.

I am unable to locate the base jsons, and I am unable to use the rake task `data:export:jsons` because I can't run `data:download` since I do not have access to the spreadsheets.

Could you help please?

**Comment by jmarrec** [comment]
Hum seems I was able to manually download them from https://drive.google.com/drive/folders/1x7yEU4jnKw-gskLBih8IopStwl0KAMEi and place them in the data/standards folder. Maybe that'll work.

**Comment by jmarrec** [comment]
Oh I see, all standards json are now in their respective folder, like NECB does (but with a different format). I think I figured it out... https://github.com/NREL/OpenStudio/pull/4850

**Comment by jmarrec** [comment]
Is the 189.1 stuff gone now though?

**Comment by mdahlhausen** [comment]
Stds never truly supported 189.1.  .jsons copied here: https://github.com/NREL/BuildingStandardsData.  We're also in the process of moving the data to a database instead of using the spreadsheets: https://github.com/NREL/openstudio-standards/pull/1486.

**Comment by jmarrec** [comment]
Got it, thanks.
