### ISSUE TITLE
Incorrect restaurant hot water temperature schedules

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#150]
I created a restaurant prototype building with the [Create DOE Prototype Building](https://bcl.nrel.gov/node/83591) measure and noticed that the target temperature schedules for the hot water are (1) missing their Schedule Types and (2) are setting the target temperature to 49°C and -9.14°C  (not the desired 60°C and 82.2°C in the [PNNL .idf of the Restaurant Prototype](https://www.energycodes.gov/development/commercial/prototype_models)).  Perhaps an issue with adding service hot water to models?

**Comment by asparke2** [comment]
Good catch.  We're planning to do a much more detailed checking of the models coming up soon, which will hopefully allow us to fix this type of thing.

**Comment by mdahlhausen** [comment]
this appears to be fixed in the most recent regression models
