### ISSUE TITLE
Lighting schedule occupancy sensor adjustment factor equation question

### ISSUE THREAD

**Issue by Nigusse** [NREL/openstudio-standards#1506]
I saw lighting adjustment factor calculation equation when reviewing the 90.1-PRM-2019 method of baseline creation. I was trying to understand the message `Creating a new lighting schedule that applies occupancy sensor adjustment factor: 0.45 based on HotelLarge BLDG_LIGHT_GUESTROOM_SCH_2010 schedule` reported to `out.osw` file.  The review process led me to the equation [below](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.SpaceType.rb#L555): 

`space_lighting_per_area = lighting_per_length * space_height + lighting_per_area` 

This equation does not have the variables dimensionally consistent. The first term is in `W` and the second term is in `W/ft2`. 

For dimensional consistency the equation should be:

`space_lighting_per_area = lighting_per_length / space_height + lighting_per_area` 

Am I missing something here? I am not familiar with this section of the code.

**Comment by dmaddoxwhite** [comment]
I believe this is for an atrium space, which has a secondary component based on the height of the space. So I think it should be:
space_lighting_per_area = lighting_per_length * space_height / space_area + lighting_per_area

**Comment by Nigusse** [comment]
@dmaddoxwhite Thanks. I agree with the proposed changes.
