### ISSUE TITLE
Update BTAP/NRCAN regression models to OS v3.6

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#1508]

**Comment by ckirney** [comment]
I have merged master and nrcan branch into nrcan_os360 and ran the testing with OpenStudio 3.6.0.  While some tests failed, all of the NRCan tests passed.  @mdahlhausen, should I submit a pull request for nrcan_os360 into master?

**Comment by ckirney** [comment]
Also, once v1.6.0 of the OpenStudioApp is released, NRCan will switch to using OS 3.6.0 for openstudio-standards development.

**Comment by ckirney** [comment]
I submitted a pull request updating these along with nrcan branch changes.  See the link below:
https://github.com/NREL/openstudio-standards/pull/1520
