### ISSUE TITLE
Infiltration rates hard-coded, they  should be created from the  standards google file

### ISSUE THREAD

**Issue by phylroy** [NREL/openstudio-standards#151]
How to reproduce: 
1. Open any archetype in the most recent model editor. 
2. Go to the space type tab and click 'General'
3. Notice there is no infiltration object defined. 

The infiltration should be set to 0.049225 Infiltration per Exterior Area (ft^3/min*ft^2 ext)
See col AB in the OpenStudio_standards.xlsx file.

**Comment by jblake59** [comment]
It would be useful to mention what the most recent model editor version is just in-case bugs sit around unresolved over version releases. I assume that the above description is referring to OS v 2.0.0.

**Comment by phylroy** [comment]
Looks like this is working.. It is not grabbing from the Spreadsheet, but hardcoded. Should grab data from xls file... Downgraded to feature request.
