### ISSUE TITLE
fuel sources for systems and boilers are not always compatible

### ISSUE THREAD

**Issue by khaddad** [NREL/openstudio-standards#154]
The fuel source for system heating coils and boilers need to be compatible

**Comment by khaddad** [comment]
OpenStudio has only electric or gas system level coils. In case the boiler is oil fired, a gas coil could be defined at the system level. In this case we need to associate the gas consumption at the system level to oil instead.

**Comment by phylroy** [comment]
Assuming this is closed.  Kamel submitted a fix.
