### ISSUE TITLE
Remove HVAC curve coefficients from Prototype.hvac_systems

### ISSUE THREAD

**Issue by asparke2** [NREL/openstudio-standards#161]
Now that OpenStudio's HVAC components come with default curves, use those curves.  They will generally be changed by the `apply_hvac_efficiency_standard()` anyway.

**Comment by mdahlhausen** [comment]
These were moved to object specific files during the HVAC refactor.  We may at some point want to move or add more curves to the spreadsheet, especially for VRF systems.
