### ISSUE TITLE
Apartment lighting schedules

### ISSUE THREAD

**Issue by cmsavage** [NREL/openstudio-standards#1618]
The ASHRAE midrise and highrise apartment lighting schedules (both named `LTG_APT_SCH` in [this file](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/comstock_doe_ref_1980_2004/data/ashrae_90_1.schedules.json), for example) seem unusually low, peaking at only 0.18 in the evening, and there is an inconsistency in this schedule between the various DOE residential prototypes scattered across the web.  It is unclear where this schedule comes from: the [google spreadsheet](https://docs.google.com/spreadsheets/d/15-mlZrWbA4srtFHtWRP1dgPeuI5plFdjCb1B79fEukI/edit?usp=sharing) states that all the 90.1 schedules in openstudio-standards are taken from the 2004 DOE prototype models, but the apartment prototype models on the [DOE page](https://www.energy.gov/eere/buildings/commercial-reference-buildings) have a different, much higher lighting fraction schedule (by a factor of approximately 5).

The midrise and highrise apartment prototype models on [energycodes.gov](https://www.energycodes.gov/prototype-building-models) have the same very low lighting schedule (generated from openstudio-standards?), but the single-family and lowrise apartment prototypes on that page have a much higher lighting schedule (again, by a factor of approximately 5).

Further discussion [here](https://discourse.ladybug.tools/t/ashrae-lighting-schedules/22763).

**Comment by mdahlhausen** [comment]
The schedule matches the recent DOE/PNNL prototype models. I don't think the schedule is realistic, but it isn't a bug. We may update the schedule to more reasonable values in the future.
