### ISSUE TITLE
Code coverage question

### ISSUE THREAD

**Issue by antonszilasi** [NREL/openstudio-standards#162]
Dear all,

Probably I am missing something but what does the code coverage icon of this git repo mean exactly? At the moment its at 28% but 28% of what?

Many thanks!

**Comment by MatthewSteen** [comment]
This isn't the place for questions, just bugs. See...

* https://www.openstudio.net/forum
* https://openstudio.uservoice.com/forums/308629-openstudio

...and

* https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=code+coverage

**Comment by antonszilasi** [comment]
@MatthewSteen 
 I thought it meant the code coverage of the various codes, ASHRAE 90.1 etc thanks!

**Comment by MatthewSteen** [comment]
Oh, I see how there might be confusion there! Here the energy codes are referred to as "standards".
