### ISSUE TITLE
Fatal error CheckForRunawayPlantTemps

### ISSUE THREAD

**Issue by padmassun** [NREL/openstudio-standards#165]
The errors (see **Error Log**) are for the pairs of building and weather files (see **Building and Weather pairs**). Please see the [attached file](https://github.com/NREL/openstudio-standards/files/746054/output.zip) which contains a pair of weather file and a building type that produces this fatal error found in eplusout.err: "CheckForRunawayPlantTemps: Simulation terminated because of run away plant temperatures, too hot"

### Error Log
````ruby
/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/jobs/run_energyplus/run_energyplus.rb failed with EnergyPlus Terminated with a Fatal Error. Check eplusout.err log., /opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/jobs/run_energyplus/run_energyplus.rb:226:in `call_energyplus'/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/jobs/run_energyplus/run_energyplus.rb:116:in `perform'/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/run.rb:211:in `run_energyplus'/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/run.rb:189:in `step'/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/run.rb:147:in `run'/mnt/openstudio/simulate_data_point.rb:163:in
````

````ruby
Found error in state 'energyplus' with message ["/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/jobs/run_energyplus/run_energyplus.rb failed with EnergyPlus Terminated with a Fatal Error. Check eplusout.err log., /opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/jobs/run_energyplus/run_energyplus.rb:226:in `call_energyplus'\n/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/jobs/run_energyplus/run_energyplus.rb:116:in `perform'\n/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/run.rb:211:in `run_energyplus'\n/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/run.rb:189:in `step'\n/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/run.rb:147:in `run'\n/mnt/openstudio/simulate_data_point.rb:163:in `':/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/jobs/run_energyplus/run_energyplus.rb:241:in `rescue in call_energyplus'\n/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/jobs/run_energyplus/run_energyplus.rb:248:in `call_energyplus'\n/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/jobs/run_energyplus/run_energyplus.rb:116:in `perform'\n/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/run.rb:211:in `run_energyplus'\n/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/run.rb:189:in `step'\n/opt/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/OpenStudio-workflow-gem-ca6ec0037615/lib/openstudio/workflow/run.rb:147:in `run'\n/mnt/openstudio/simulate_data_point.rb:163:in `'"]}
````

### Building and Weather pairs
**FullServiceRestaurant**   'CAN_PQ_Baie.Comeau.711870_CWEC.epw' , 'CAN_BC_Prince.George.718960_CWEC.epw' , 'CAN_BC_Sandspit.711010_CWEC.epw' , 'CAN_NF_Stephenville.718150_CWEC.epw' , 'CAN_NS_Sable.Island.716000_CWEC.epw' , 'CAN_PQ_Sept-Iles.718110_CWEC.epw'

**Outpatient**  'CAN_AB_Calgary.718770_CWEC.epw' , 'CAN_AB_Edmonton.711230_CWEC.epw' , 'CAN_AB_Fort.McMurray.719320_CWEC.epw' , 'CAN_AB_Grande.Prairie.719400_CWEC.epw' , 'CAN_AB_Lethbridge.712430_CWEC.epw' , 'CAN_AB_Medicine.Hat.718720_CWEC.epw' , 'CAN_BC_Abbotsford.711080_CWEC.epw' , 'CAN_BC_Cranbrook.718800_CWEC.epw' , 'CAN_BC_Fort.St.John.719430_CWEC.epw' , 'CAN_BC_Kamloops.718870_CWEC.epw' , 'CAN_BC_Port.Hardy.711090_CWEC.epw' , 'CAN_BC_Prince.George.718960_CWEC.epw' , 'CAN_BC_Prince.Rupert.718980_CWEC.epw' , 'CAN_BC_Sandspit.711010_CWEC.epw' , 'CAN_BC_Smithers.719500_CWEC.epw' , 'CAN_BC_Summerland.717680_CWEC.epw' , 'CAN_MB_Brandon.711400_CWEC.epw' , 'CAN_MB_Churchill.719130_CWEC.epw' , 'CAN_MB_The.Pas.718670_CWEC.epw' , 'CAN_MB_Winnipeg.718520_CWEC.epw' , 'CAN_NB_Fredericton.717000_CWEC.epw' , 'CAN_NB_Miramichi.717440_CWEC.epw' , 'CAN_NB_Saint.John.716090_CWEC.epw' , 'CAN_NF_Gander.718030_CWEC.epw' , 'CAN_NF_Goose.718160_CWEC.epw' , 'CAN_NF_St.Johns.718010_CWEC.epw' , 'CAN_NF_Stephenville.718150_CWEC.epw' , 'CAN_NS_Greenwood.713970_CWEC.epw' , 'CAN_NS_Sable.Island.716000_CWEC.epw' , 'CAN_NS_Shearwater.716010_CWEC.epw' , 'CAN_NS_Sydney.717070_CWEC.epw' , 'CAN_NT_Inuvik.719570_CWEC.epw' , 'CAN_NU_Resolute.719240_CWEC.epw' , 'CAN_ON_London.716230_CWEC.epw' , 'CAN_ON_North.Bay.717310_CWEC.epw' , 'CAN_ON_Ottawa.716280_CWEC.epw' , 'CAN_ON_Sault.Ste.Marie.712600_CWEC.epw' , 'CAN_ON_Thunder.Bay.717490_CWEC.epw' , 'CAN_ON_Timmins.717390_CWEC.epw' , 'CAN_ON_Toronto.716240_CWEC.epw' , 'CAN_ON_Trenton.716210_CWEC.epw' , 'CAN_ON_Windsor.715380_CWEC.epw' , 'CAN_PE_Charlottetown.717060_CWEC.epw' , 'CAN_PQ_Bagotville.717270_CWEC.epw' , 'CAN_PQ_Baie.Comeau.711870_CWEC.epw' , 'CAN_PQ_Kuujjuarapik.719050_CWEC.epw' , 'CAN_PQ_Kuujuaq.719060_CWEC.epw' , 'CAN_PQ_La.Grande.Riviere.718270_CWEC.epw' , 'CAN_PQ_Lake.Eon.714210_CWEC.epw' , 'CAN_PQ_Mont.Joli.717180_CWEC.epw' , 'CAN_PQ_Montreal.Intl.AP.716270_CWEC.epw' , 'CAN_PQ_Quebec.717140_CWEC.epw' , 'CAN_PQ_Riviere.du.Loup.717150_CWEC.epw' , 'CAN_PQ_Roberval.717280_CWEC.epw' , 'CAN_PQ_Schefferville.718280_CWEC.epw' , 'CAN_PQ_Sept-Iles.718110_CWEC.epw' , 'CAN_PQ_Sherbrooke.716100_CWEC.epw' , 'CAN_PQ_St.Hubert.713710_CWEC.epw' , 'CAN_PQ_Ste.Agathe.des.Monts.717200_CWEC.epw' , 'CAN_PQ_Val.d.Or.717250_CWEC.epw' , 'CAN_SK_Estevan.718620_CWEC.epw' , 'CAN_SK_North.Battleford.718760_CWEC.epw' , 'CAN_SK_Regina.718630_CWEC.epw' , 'CAN_SK_Saskatoon.718660_CWEC.epw' , 'CAN_SK_Swift.Current.718700_CWEC.epw' , 'CAN_YT_Whitehorse.719640_CWEC.epw'

**SecondarySchool** 'CAN_BC_Abbotsford.711080_CWEC.epw' , 'CAN_BC_Comox.718930_CWEC.epw' , 'CAN_BC_Port.Hardy.711090_CWEC.epw' , 'CAN_BC_Prince.George.718960_CWEC.epw' , 'CAN_BC_Prince.Rupert.718980_CWEC.epw' , 'CAN_BC_Sandspit.711010_CWEC.epw' , 'CAN_BC_Smithers.719500_CWEC.epw' , 'CAN_BC_Vancouver.718920_CWEC.epw' , 'CAN_BC_Victoria.717990_CWEC.epw' , 'CAN_NB_Saint.John.716090_CWEC.epw' , 'CAN_NS_Sable.Island.716000_CWEC.epw' , 'CAN_NS_Shearwater.716010_CWEC.epw' , 'CAN_PQ_Baie.Comeau.711870_CWEC.epw' , 'CAN_PQ_Lake.Eon.714210_CWEC.epw' , 'CAN_PQ_Riviere.du.Loup.717150_CWEC.epw' , 'CAN_PQ_Sept-Iles.718110_CWEC.epw' , 'CAN_YT_Whitehorse.719640_CWEC.epw'

### Additional Details for the attached file
Vintage: NECB 2011
Building Type: FullServiceRestaurant, Outpatient, SecondarySchool
Climate Zone: NECB HDD Method
EPW file: CAN_BC_Prince.George.718960_CWEC.epw

Models generated by `openstudio-standards\openstudio-standards\test\test_necb_bldg_<building_name>.rb`

**Comment by phylroy** [comment]
Hey Guys,

Did a quick search on Unmet hours and found this *sort of* solution. 

https://unmethours.com/question/20606/plant-loop-exceeding-upper-temperature-limit/?answer=20612#post-id-20612

One is to set the controller to intermittant...which I think we already have set.... The other is to use a E+ controller.  Which would be painful to implement for the standards work. (The standards work relies on a single OS 'measure'. So this would not be feasible easily.

I found the issue request here that seems to hit the nail on what we need. Maybe Kamel you could chat with Kyle to see what the solution would be best for the short term and then keep a long term solution in the issue tracker?

https://github.com/NREL/OpenStudio/issues/2410

**Comment by khaddad** [comment]
Checked with Andrew at NREL for a possible solution and he indicated that implementing a new set-point manager will take some time. Submitted an e+ ticket related to this issue for them to address the issue with the constant speed pump coming on even when there is no load in the load at the baseboards.

**Comment by phylroy** [comment]
Waiting on NREL/OpenStudio#2410
