### ISSUE TITLE
Corrections to data in WeatherData1 array

### ISSUE THREAD

**Issue by jblake59** [NREL/openstudio-standards#169]
Mike Lubun reported problems with some of the data in the WeatherData1 array that was extracted from Weather.model.rb and placed in an Excel spreadsheet for easier review.  The following changes need to be made:

**Calgary:** 
heating_coil_type_sys4: 'Electric' -> 'Gas'
heating_coil_type_sys6: 'Electric' -> 'Hot Water'

**Inuvik:** 
boiler_fueltype: 'FuelOil#1' -> 'FuelOil#2'

**Resolute:** 
hdd18: 12_570 -> 12570     @phylroy : I assume the "_" character insertion was an import error?
boiler_fueltype: 'FuelOil#2' (This is already FuelOil#2 so no actual change required!)

**Whitehorse:** 
boiler_fueltype: 'FuelOil#1' -> 'FuelOil#2'

**Comment by phylroy** [comment]
Looks good...Mike does this make sense?
