### ISSUE TITLE
Wrong design supply temperatures for FullServiceRestaurant, LargeOffice, MediumOffice, QuickServiceRestaurant and SmallOffice

### ISSUE THREAD

**Issue by padmassun** [NREL/openstudio-standards#171]
Here is the error message generated by BTAPResults' Json file
````
"[ERROR][TEST-FAIL][NECB2011-?]:[ZONE][Sys-0 Flr-X Sch-- undefined - HPlcmt-core] cooling_design_supply_temp expected value:14.0 == result value:13.0",
"[ERROR][TEST-FAIL][NECB2011-?]:[ZONE][Sys-0 Flr-X Sch-- undefined - HPlcmt-core] heating_design_supply_air_temp expected value:40.0 == result value:43.0",
````
where the X in `Sys-0 Flr-X` above is the floor number.

**Comment by phylroy** [comment]
Related to #173

**Comment by khaddad** [comment]
- undefined - zones are free floating and have no heating or cooling. For NECB we're using a design cooling temperature of 13 DegC and heating temperature of 43 DegC which are different from the defaults of 14 and 40 DegC. This has has no impact on the results since these zones are not conditioned.

**Comment by phylroy** [comment]
Modify the BTAPResult to skip  undefined spaces.  Do this for infiltration as well.

**Comment by phylroy** [comment]
Padmassun to deouble check
