### ISSUE TITLE
Create DOE Prototype Building missing Canadian climate files

### ISSUE THREAD

**Issue by cfrankowski** [NREL/openstudio-standards#1710]
I'm attempting to use the Create DOE Prototype Building Measure in OpenStudio Application V 1.7.0+b070178884.
Specifically using NECB 2011 with a Climate File. 

I believe the measure uses this code to generate the list of weather files:
https://github.com/NREL/openstudio-standards/blob/18e3a888f58191a8dcd75a9749f639a4619340b6/lib/openstudio-standards/weather/Weather.Model.rb#L353

I would expect the list to include the weather files found here:
https://github.com/NREL/openstudio-standards/tree/v0.5.0/data/weather

But the dropdown doesn't include any of the Canadian weather files from that folder (e.g. CAN_BC_Kelowna.Intl.AP.712030_CWEC2016.epw)
![NECB issue](https://github.com/NREL/openstudio-standards/assets/1744767/a168d91e-5b8f-43c2-992a-466ee66e6520)
It looks like all of the other files match.

My understanding is that this library (v0.5) gets included in the OpenStudio SDK (v3.7.0), which is used by OpenStudio Application (v1.7). I'm not sure at which stage the Canadian weather files are getting dropped.

Apologies if this issue isn't related with this specific library.

Thanks!

**Comment by mdahlhausen** [comment]
@cfrankowski the method that gets the available [canadian weather files is here](https://github.com/NREL/openstudio-standards/blob/v0.5.0/lib/openstudio-standards/weather/Weather.Model.rb#L345-L360). Note there is a slight difference in the method call depending on whether you are running the measure through the OS CLI or through Ruby. We removed a lot of the Canadian weather files recently to reduce the gem install size. It's possible you have a newer version of the gem installed.  That's one thing to check.

Going forward, we aren't planning to support the Create DOE Prototype Building measure with Canadian weather files. Use the create_typical method instead, and couple it with the change building location measure, which can set the weather information to any location you have weather data for.
