### ISSUE TITLE
Wrong Attic Infiltration Flow per m2 for SmallOffice

### ISSUE THREAD

**Issue by padmassun** [NREL/openstudio-standards#173]
Here is the error message generated by BTAPResults' Json file

````json
"SmallOffice": [
    "[ERROR][TEST-FAIL][NECB2011-Section 8.4.3.6]:[SPACE][Attic]-infiltration_flow_per_m2 expected value:0.00023 == result value:0.00025"
  ]
````

**Comment by phylroy** [comment]
Undefined spaces are not set to the correct infiltration rates.. this may be present with the plenums.

**Comment by IainMacdonald** [comment]
Nice catch. OpenStudio is in line with the testing standards and protocols in place in north America (i.e. full building envelope area). We should probably update the code to include all six sides and exposed floors (eventually)!

For the attic - surely this is outside the air barrier so the infiltration rate should be something else?

**Comment by phylroy** [comment]
Hmm the the NECB 2011 rule diagnostic will need to change then to accommodate.  I'll reassign later and reduce this to a normal priority.

**Comment by khaddad** [comment]
agree, Iain, the code should be updated to include different rates for surfaces outside the air barrier.
