### ISSUE TITLE
Harmonize Fuel Utility data with Fuel Selection by location

### ISSUE THREAD

**Issue by phylroy** [NREL/openstudio-standards#174]
I've notice a bit of the mismatch between this
1)
https://github.com/NREL/openstudio-standards/blob/nrcan/openstudio-standards/lib/openstudio-standards/btap/FutureUse_Weather-System_Data.xlsx

and this

2)
https://github.com/NREL/OpenStudio-measures/blob/nrcan/NRCAN_working_measures/BTAPUtilityTariffs/resources/utility_tariffs.csv

Some selections in 1) conflict with 2) (The xlsx file says to use a fuel, but the csv filein 2) does not have a cost. )  

Work with Mike to make sure that the fuel selection for the region is aligned.

**Comment by phylroy** [comment]
Modified test here to showcase...(run with Ruby, ensure that you have the correct openstudio-standards gem for the nrcan branch installed for you system. 



 to showcase problem.. Test will run school in two locations.. The resolute location is told to use gas, but there is no gas cost for that location, so the simulation reports cost for gas to be zero.  Either Resolute should not use gas, or there should be a cost for gas.

**Comment by phylroy** [comment]
Mike is harmonizing the spreadsheet and Kamel will update the hash in weather. 

Potentially remove utility rates which are zero, and provide an error message to the user.

**Comment by jblake59** [comment]
Jeff updated Resolute to Electricity as directed by Mike.

**Comment by phylroy** [comment]
Is this resolved.

**Comment by jblake59** [comment]
Mike says it's resolved.
