### ISSUE TITLE
File paths too long

### ISSUE THREAD

**Issue by asparke2** [NREL/openstudio-standards#1740]
Windows has a path limit of 256 characters. Some of the files, particularly those in the `/test` directory, can exceed that path limit on Windows, depending on the root directory for the GitHub repo. It's mainly long file names, not nested directory structures, that make the paths long.  See example below:

This path - 205 characters - is a local manual checkout of openstudio-standards
`C:\GitRepos\openstudio-standards\test\necb\building_regression_tests\expected_results\FullServiceRestaurant-NECB2011-NaturalGasHPElecBackupMixed-CAN_AB_Calgary.Intl.AP.718770_CWEC2016_expected_result.osm`

This path - 263 characters - is from when openstudio-standards is cloned by bundler when the gem is installed from GitHub:
`C:\GitRepos\ComStock\.custom_gems\ruby\3.2.0\bundler\gems\openstudio-standards-51a6c20996ff\test\necb\building_regression_tests\expected_results\FullServiceRestaurant-NECB2011-NaturalGasHPElecBackupMixed-CAN_AB_Calgary.Intl.AP.718770_CWEC2016_expected_result.osm`

The filenames don't need to get a whole lot shorter, so in the near term some simple, small changes would help immensely.

**Comment by asparke2** [comment]
Current workaround is to check out the https://github.com/NREL/openstudio-standards/tree/delete_long_tests branch, which simply deletes the longest-named files. This branch can be updated to whatever the desired commit is.

**Comment by mdahlhausen** [comment]
Resolved with #1767
