### ISSUE TITLE
missing Geometry for Large Hotel

### ISSUE THREAD

**Issue by mlubun** [NREL/openstudio-standards#176]
This is related to the floor multiplier error.   The large hotel is missing the interior suites from floor 2 to 5.   only the corner suites are correct (except the multiplier is missing)

**Comment by phylroy** [comment]
For 'LargeHotel', 'MidriseApartment', 'LargeOffice'

Check to see if the osm file contains the zone multipliers for the spaces listed by the  def define_space_multiplier  in the appropriate "Prototype.<building_type>.rb file. 



For example for the Prototype.large_hotel.rb file. You will find this method. 

`    space_multiplier_map = {
      'Room_1_Flr_3' => 4,
      'Room_2_Flr_3' => 4,
      'Room_3_Mult19_Flr_3' => 76,
      'Room_4_Mult19_Flr_3' => 76,
      'Room_5_Flr_3' => 4,
      'Room_6_Flr_3' => 4,
      'Corridor_Flr_3' => 4,
      'Room_3_Mult9_Flr_6' => 9
    }`

When you create the model with test_necb_large_office.rb (sp?) Use sketchup to validate that the thermal zone was created with the correct mulitplier. 

Note the thermal zone will have a different syntax like "Sp-**Room_3_Mult19_Flr_3** Sys-1 Flr-1 Sch-F HPlcmt-south ZN"

**Comment by phylroy** [comment]
With respect to the zoning strategies we were talking about last friday.. I created a bit of a hybrid of the zoning to deal with the zonal multipliers.. The auto-zone method will still try to group similar spaces into zones.. but when it encounters a space with a multiplier..it will keep that as its own zone.  Hopefully this will give us the best of both approaches without having a zone for every space.

**Comment by padmassun** [comment]
RE: Large Hotel

One of the rooms that I am looking at has a multiplier of 1, but the multiplier is supposed to be 76.
![image](https://cloud.githubusercontent.com/assets/24966493/23409422/90aec53a-fd99-11e6-902d-63084619ea9c.png)

This is similar for all the cases of 
`      'Room_1_Flr_3' => 4,
      'Room_2_Flr_3' => 4,
      'Room_3_Mult19_Flr_3' => 76,
      'Room_4_Mult19_Flr_3' => 76,
      'Room_5_Flr_3' => 4,
      'Room_6_Flr_3' => 4,
      'Corridor_Flr_3' => 4,
      'Room_3_Mult9_Flr_6' => 9`

**Comment by phylroy** [comment]
How are you generating the files? using test_necb_bldg_*.rb?

**Comment by padmassun** [comment]
yes

**Comment by padmassun** [comment]
RE Midrise Apartment:
One of the rooms that I am looking at has a multiplier of 1, but the multiplier is supposed to be 2
![image](https://cloud.githubusercontent.com/assets/24966493/23410352/f69f8930-fd9c-11e6-9a56-75d0f19d6161.png)

this is similar for all the cases of 
`      'M SW Apartment' => 2,
      'M NW Apartment' => 2,
      'M SE Apartment' => 2,
      'M NE Apartment' => 2,
      'M N1 Apartment' => 2,
      'M N2 Apartment' => 2,
      'M S1 Apartment' => 2,
      'M S2 Apartment' => 2,
      'M Corridor' => 2`

**Comment by padmassun** [comment]
RE LargeOffice:
One of the rooms that I am looking at has a multiplier of 1, but the multiplier is supposed to be 10

![image](https://cloud.githubusercontent.com/assets/24966493/23410761/36b27144-fd9e-11e6-9c0d-e659e5c3ddc9.png)

this is similar for all the cases of
`      'DataCenter_mid_ZN_6' => 10,
      'Perimeter_mid_ZN_1' => 10,
      'Perimeter_mid_ZN_2' => 10,
      'Perimeter_mid_ZN_3' => 10,
      'Perimeter_mid_ZN_4' => 10,
      'Core_mid' => 10,
      'MidFloor_Plenum' => 10`

**Comment by phylroy** [comment]
Latest Commit should fix it. Please test again, thanks for the catch!
