### ISSUE TITLE
90.1-2010 BETA ERROR SolarCollectorFlatPlatWater

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/openstudio-standards#180]
Running the current version of the Create Baseline Building measure from the BCL with Apply Measure Now in 1.14.0 produces the following error.

```
ERROR The run failed with the following severe or fatal errors:  ** Severe  ** IP: IDF line~7427 Error detected in Object=SOLARCOLLECTOR:FLATPLATE:WATER, name=SOLAR COLLECTOR FLAT PLATE WATER   **   ~~~   ** Field
```

**Comment by asparke2** [comment]
Not sure how this object got into the model, assume it was in the Proposed model?  @MatthewSteen can you send me the .osm if you happen to have it by chance?
