### ISSUE TITLE
How to use last release of openstudio-standards?

### ISSUE THREAD

**Issue by ainar** [NREL/openstudio-standards#1815]
Hello,
I got this issue with Create doe prototype building: https://github.com/NREL/openstudio-model-articulation-gem/issues/145

I have seen that I use openstudio-standards 0.6.1, but the latest release is 0.6.3. So it may be the culprit.
Despite following the instructions [here](https://github.com/NREL/openstudio-standards/blob/master/docs/UserQuickStartGuide.md), it seems the version of the gem is still 0.6.1 (it is written in the error log).

**Comment by mdahlhausen** [comment]
Seems like a file path issue. Testing fix with #1816
