### ISSUE TITLE
Test Conditioned and Unconditioned Spaces

### ISSUE THREAD

**Issue by phylroy** [NREL/openstudio-standards#183]
I've noticed some conditioned and unconditioned warnings in some of the output in the past. 
Do a  scan to determine if all the models spaces: 
1) Have a spacetype
2) Are part of a zone
3) If the spacetype == undefined then the associated thermalzone should not be conditioned, else the thermalzone should be conditioned.  
 
Write a test around this in the QAQC of BTAPResults.

**Comment by padmassun** [comment]
please see https://github.com/padmassun/OpenStudio-measures/commit/0bf82fa81e8daff9855cc026078d6e5634070134

**Comment by phylroy** [comment]
Looks good, however this is more for a sanity check than an NECB rule. 

Also this line will cause problems...you should use the spacetype name..not the space name.

**Comment by padmassun** [comment]
see https://github.com/NREL/OpenStudio-measures/commit/437444d50992e584b6f39d1f346b3251e24a97d5
