### ISSUE TITLE
Test for NECB 8.4.2.6

### ISSUE THREAD

**Issue by phylroy** [NREL/openstudio-standards#184]
For each space in the model
 1) iterate through each surface.
 2) determine if there is a space on the other side (is it an interior partition?)
 3) If so...does the setpoint temperature difference between the two spaces ever exceed 10C?
 4) If true set conductance of surface according to the formula in NECB 3.2.1.3,  else,  set the surface to adiabatic type and assign a default construction directly to the surface. 

Develop a method within the compliance.rb file in btap to do this and write a test for it in the test folder of the openstudio-standards project. 

Why are we doing this? This is a NECB rule, but adiabatic surfaces are exempt from the simulation calculation..so this may shave some time off the runs.

**Comment by phylroy** [comment]
See the method here for inspiration for step 2. 
https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.Space.rb#L1996

**Comment by padmassun** [comment]
see https://github.com/NREL/openstudio-standards/commit/535da28430eba1eecb481d701d43cdd5d51cd234

The conductance of surfaces has not been changed. This test method only determines and outputs the maximum setpoint temperature difference between the two spaces/surfaces

**Comment by padmassun** [comment]
@phylroy  please review https://github.com/NREL/openstudio-standards/commit/2c47841ee01ee06b19da13a55a3bb240475aff71
