### ISSUE TITLE
Method to determine above and below stories in model. 

### ISSUE THREAD

**Issue by phylroy** [NREL/openstudio-standards#187]
Develop two methods in geometry.rb to determine how many stories are above ground and how many are below ground.   Current methods only determine total stories.  This will be need to be used in Compliance.rb for system selection.

**Comment by padmassun** [comment]
please see https://github.com/NREL/openstudio-standards/commit/f60f39deffa86211d479f55981a26bcaa959c2dd

**Comment by phylroy** [comment]
1. Create a csv file (or json file if you wish) that contains the osmfilename, above stories, below_ground stories in rows. 

In Pseudo code within the unit test. 

expected_results_hash = Json.Parse(File.read('your_json_file.json')))
error_string_array = []
files = Load all files in data/geometry into array of paths strings
files.each  do |file|
#load model
model = BTAP::FileIO:load_osm( file ) 
# do your check with your methods and set them to variables. 
# convert the long file name to the basename (just the file name and not the full path) see https://ruby-doc.org/core-2.2.0/File.html#method-c-basename  
# look up the values for the basement and above ground expected values in the expected_results_hash. I would rearrange your json format so you could write expected_results_hash[basefilename][belowGround]
#Report error if file is not found in expected results. 
#Check if values are the same, if not add error message to error_string_array 
#end loop
#check if  error_string_array.size > 0 then puts error_string_array and return false else return true.
