### ISSUE TITLE
Wrong typical heating setpoint schedule for MediumOffice  

### ISSUE THREAD

**Issue by sarocu** [NREL/openstudio-standards#192]
The prototypes_inputs json file lists typical_heating_setpoint as "HTGSETP_SCH_PACU_VAV_bot" for MediumOffice building types in the 90.1 templates; in the standards schedules json file, the schedule is named "OfficeMedium HTGSETP_SCH_NO_OPTIMUM" instead.

This causes searches using model.find_objects($os_standards['schedules'], search_criteria) to fail.

**Comment by lymereJ** [comment]
This issue has been fixed along the way.
