### ISSUE TITLE
Space type name does not match with space type on excel sheet for SmallHotel

### ISSUE THREAD

**Issue by padmassun** [NREL/openstudio-standards#193]
````
/home/nrcan/windows-host/projects/OpenStudio-measures/NRCAN_working_measures/BTAPResults/resources/necb_2011_spacetype_info.csv
Zero matches found for [{2=>"Storage area - occsens", 1=>"Space Function"}]
space type of [Storage area - occsens] and/or building type of [Space Function] was not found in the excel sheet for space: [FrontStorageFlr1]
Zero matches found for [{2=>"Storage area - occsens 3", 1=>"Space Function"}]
space type of [Storage area - occsens 3] and/or building type of [Space Function] was not found in the excel sheet for space: [FrontStorageFlr4]
Zero matches found for [{2=>"Storage area - occsens 1", 1=>"Space Function"}]
space type of [Storage area - occsens 1] and/or building type of [Space Function] was not found in the excel sheet for space: [FrontStorageFlr2]
Zero matches found for [{2=>"Storage area - occsens 8", 1=>"Space Function"}]
space type of [Storage area - occsens 8] and/or building type of [Space Function] was not found in the excel sheet for space: [RearStorageFlr4]
Zero matches found for [{2=>"Storage area - occsens 6", 1=>"Space Function"}]
space type of [Storage area - occsens 6] and/or building type of [Space Function] was not found in the excel sheet for space: [RearStorageFlr2]
Zero matches found for [{2=>"Storage area - occsens 2", 1=>"Space Function"}]
space type of [Storage area - occsens 2] and/or building type of [Space Function] was not found in the excel sheet for space: [FrontStorageFlr3]
Zero matches found for [{2=>"Storage area - occsens 4", 1=>"Space Function"}]
space type of [Storage area - occsens 4] and/or building type of [Space Function] was not found in the excel sheet for space: [LaundryRoomFlr1]
Zero matches found for [{2=>"Storage area - occsens 7", 1=>"Space Function"}]
space type of [Storage area - occsens 7] and/or building type of [Space Function] was not found in the excel sheet for space: [RearStorageFlr3]
Zero matches found for [{2=>"Storage area - occsens 5", 1=>"Space Function"}]
space type of [Storage area - occsens 5] and/or building type of [Space Function] was not found in the excel sheet for space: [RearStorageFlr1]

````

**Comment by padmassun** [comment]
````
template	building_type	space_type	lighting_per_area_w_per_m2	occupancy_per_area_people_per_m2	occupancy_schedule	electric_equipment_per_area_w_per_m2	service_water_heating_peak_flow_per_area_gal_per_h_ft2
NECB 2011	Space Function	Storage area	6.799936823	0.010010441	NECB-E-Occupancy	0.999990712	0.00142675
NECB 2011	Space Function	Storage area - refrigerated	6.799936823	0.010010441	NECB-E-Occupancy	0.999990712	0.00142675
````
Please change the name of space type to match the ones on the excel sheet as shown above

**Comment by jblake59** [comment]
I changed the Google sheet a couple of days ago and ran the appropriate "rake data:update:manual" to update the json files. I committed and pushed these changes yesterday. I added the following new space types as part of my solution to issue #164:

Storage area - occsens
Storage area - refrigerated - occsens
Office - enclosed - occsens

Note that I DID NOT change the lighting_per_area value in the Space Types sheet. Rather, I used a factor in code and also used this factor in the space type test script! I obviously missed another test script!

**Comment by phylroy** [comment]
is this still an issue? @jblake59 did you also update the modified json files that were created?

**Comment by padmassun** [comment]
@phylroy I am thinking of working on creating a script that will update the excel file in the resources folder of BTAPResults. I have also thought about using the json files (which grabbed the data from OpenStudio_Standards.xlsx) in the BTAPResults measures to run QAQC. I think it would be a good idea to implement this method, as this would support every template (as long as the data is available in the xlsx file). I am more inclined to use the json files, as it would be more accessible format.

I did take a look at those json files, and the file "manage_OpenStudio_Standards.rb" which creates the json files. If it is possible I would like to implement a modified version of the code present to make the output json file have the data nested by templates (atleast for "Space Types" which is used as part of the qaqc verification). The modified version that I am thinking of would also do unit conversions from imperial to metric only on selected data (lighting_per_area, occupancy_per_area, electric_equipment_per_area,) which is used for qaqc verification.

**Comment by phylroy** [comment]
Hey Padmassun...There is already a rake method to update the data straight
from Google...



Also I'd rather not use the excel file as part of the qaqc...Since this
will defeat the purpose of the regression tests.

**Comment by padmassun** [comment]
Yes, I am aware of that, and the rake uses the method from "manage_OpenStudio_Standards.rb". I wanted to modify that code a bit to have the information nested by template type (atleast for Space Types)

**Comment by padmassun** [comment]
> Also I'd rather not use the excel file as part of the qaqc...Since this will defeat the purpose of the regression tests.

The excel file in the resource folder of BTAPResults was derived from OpenStudio_Standards.xlsx

**Comment by phylroy** [comment]
Exactly...Testing data should remain separate from production data.
Otherwise you could be in a situation where  bad data == bad data is true

**Comment by padmassun** [comment]
see https://github.com/NREL/OpenStudio-measures/commit/c853421bc8565dce1dffad9c34d8b6a300e520f3#diff-c5d33a28a26e30cd0f1e95fc46098ba3
