### ISSUE TITLE
Multipliers bieng applied twice for water heating on buildings with zone multipliers

### ISSUE THREAD

**Issue by mlubun** [NREL/openstudio-standards#197]
Large Office:

The space service water peak flow rate is for zones with multipliers is multiplied by the multiplier to, so 0.12 gallons/min becomes 1.2 gallons/min. in the large office case (multiplier of 10 for mid zones)   This is created for all of the zones with multipliers, however the zone multiplier (10)  multiplies this result by 10. The result is unrealistic hot water energy use.   When I changed the space service water peaks back to the default and let the zone multipliers scale it, the resultant energy use was more realistic.  A check with E+ IDF for large office with multipliers still used the Baseline or default service water peak flow rate and let the multiplier do the calculation. They are still high compared to the E+ archetype results, but that could be due to the E+ water model using a unique mains water temperature and there may be an issue with our derivation of the peak service water flow rate (m3/sec) from NECB hot water usage (W/occ).

**Comment by phylroy** [comment]
Mike: To double check Maria's calcs.
