### ISSUE TITLE
Missing Ground Temperatures" data in OpenStudio_Standards

### ISSUE THREAD

**Issue by jblake59** [NREL/openstudio-standards#200]
The following run message: **_"Could not find ground temperatures; will use generic temperatures, which will skew results."_** is being produced near the beginning of each OpenStudio run regardless of building type and weather file used. It occurs because of a check in Weather.Model.rb when it does not find monthly data in the "Ground Temperatures" sheet in "OpenStudio_Standards" Google sheet!

**Comment by jblake59** [comment]
- Need to track down what these generic climate-zone specific ground temperatures are required for NECB 2011 compliance or not.

**Comment by phylroy** [comment]
Jeff: Still needs to confirm that there are ground rules for NECB

**Comment by jblake59** [comment]
My non-exhaustive search agreed with Mike's assessment that the NECB 2011 has no requirements for ground temperature values o check isn't required.
