### ISSUE TITLE
Reference COPs for chillers

### ISSUE THREAD

**Issue by mlubun** [NREL/openstudio-standards#202]
Default COPs do not correspond to canQuest values or ASHRAE 90.1  2007 (which was used for NECB 2011)

[chiller cop 90.1 2007.docx](https://github.com/NREL/openstudio-standards/files/865935/chiller.cop.90.1.2007.docx)

**Comment by phylroy** [comment]
Mike is testing. Pending his results.

**Comment by phylroy** [comment]
Default COP was being used.. Now being set correctly. ![bitmoji](https://render.bitstrips.com/v2/cpanel/10176239-178446718_10-s4-v1.png?transparent=1&palette=1&width=246)
