### ISSUE TITLE
Unused zones to be deleted in Medium Office

### ISSUE THREAD

**Issue by jiangithub** [NREL/openstudio-standards#204]
A number of unused thermal zones in Medium Office models need to be deleted. They 
Errors were found when viewing the model in Sketchup. The zone names are used in in Daylighting:Controls objects. 
![image](https://cloud.githubusercontent.com/assets/8917710/24376402/9eeef914-12f0-11e7-80e0-9a167a0d0b96.png)

**Comment by asparke2** [comment]
@jiangithub Can you double-check in the IDF file itself?  I don't see any extra zones in the IDF or the HTML file (see below).  I wonder if this is actually a bug in the way that SketchUp shows the zones.

![image](https://cloud.githubusercontent.com/assets/2009290/24475127/27f58d8a-148c-11e7-97d7-fb3199ffeca5.png)

**Comment by jiangithub** [comment]
Those appear in the idf files. I don't see them in the OSM file either. Also interesting, the same name of the zone is also used as the name of Daylighting:Controls objects in IDF and I don't see such objects in the OSM files. 

![image](https://cloud.githubusercontent.com/assets/8917710/24630290/f4beb9f8-1870-11e7-9c62-38b3ae3860bd.png)

Here are the OSM and IDF files
![image](https://cloud.githubusercontent.com/assets/8917710/24630390/60c200ec-1871-11e7-982a-d6ba0238f974.png)
