### ISSUE TITLE
SmallHotel WindowShadingControl Error

### ISSUE THREAD

**Issue by amirroth** [NREL/openstudio-standards#207]
Getting this error for ~100 windows in SmallHotel:

`   ** Severe  ** Window=D_CORRIDORFLR1_16_0_0_0_0 has Window Shading Control with
   **   ~~~   ** MeetDaylightingIlluminanceSetpoint but it is not in a Daylighting zone.
   **   ~~~   ** Zone indicated=CORRIDORFLR1 ZN`

90.1-2004 vintage. 3C climate zone.

**Comment by lymereJ** [comment]
This error is not generated anymore.
