### ISSUE TITLE
NECB 2011 Heat Recovery Compliance Test

### ISSUE THREAD

**Issue by mlubun** [NREL/openstudio-standards#208]
Section 5.2.10 of NECB 2011 indicates an HRV is required if the sensible heat content of the exhaust air system exceeds 150 kW.   Par 4 provides the calculation using the 2.5% outdoor dry bulb Jan design temperature and the exhaust air temperature.   In the QA/QC checks I use the 21C as the exhaust air temperature and the outdoor air requirements (fresh air, as this would be exhausted to maintain the air balance).   For this iteration we are not modelling the exhaust air systems, so the outside air would be the equivalent (less air leakage from the zones associated with the systems).   Our default air leakage ( 0.25 L/sec/m2 above grade wall, roof, exposed floor areas) is really small.   For the large office system with the multiplier of 10 a HRV would be required as this system is extremely large (supply air = 83,330 L/sec, OA = 15,392.62 L/sec for Churchill, resulting in a heat recovery potential of 1118.936 kW).

**Comment by phylroy** [comment]
Hey Mike, 

I am not clear on what needs to be done here.

**Comment by padmassun** [comment]
Any update on what needs to be done to solve this issue?
