### ISSUE TITLE
Strip Mall Zoning Issue

### ISSUE THREAD

**Issue by mlubun** [NREL/openstudio-standards#209]
Reference archetype is a series of 10 retail stores side by side in a long strip.   The current zoning follows a thermodynamic principle of 3 zones:   2 end unit thermal zones of 1 store each and a middle thermal zone of 8 stores.   The middle thermal zone of 8 stores is served by a single air loop with a large PSZ.   Because of the PSZ large size (cooling capacity, outdoor air, supply air) it requires an economizer and almost an HRV.    Ideally each store would have its own PSZ system, therefore each store space (separately defined), would be its own thermal zone and have its own air loop.

**Comment by phylroy** [comment]
Fixed.

**Comment by phylroy** [comment]
Mike to examine

**Comment by mlubun** [comment]
Fixed. Can close this issue
