### ISSUE TITLE
Mismatched Floor Construction in Medium Office

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#211]
Differences were found in the u factor without film of the floor at bottom between the idf models and the os models of Medium Office from the envelope test. 

The floor construction (**ext_slab_8in_with_carpet**) in the idf model consists of a "_200mm Normalweight concrete floor_" (8-in) layer and a "_CP02 carpet pad_" layer, but the floor construction (**Typical Insulated Carpeted 6in Slab Floor**) of 
os model has a "_6 in. Normalweight Concrete Floor_" with a "_Typical Carpet Pad_".  The difference between the "_CP02 carpet pad_" and the "_Typical Carpet Pad_" is only on the roughness ("Very Rough" to "Smooth"), so the major difference is on the insulated floor layer.

In the "**Material**" tab of the google standard spreadsheet, there are both "_6 in. Normalweight Concrete Floor_" and "_8 in. Normalweight Concrete Floor_".
The "**Constructions**" tab of the google spreadsheets, the "_Typical Insulated Carpeted 6in Slab Floor_" construction has a material layer of "_6 in. Normalweight Concrete Floor_", but the "_Typical Insulated Carpeted 8in Slab Floor_" construction has the material layer of "_8 in. Concrete Block Basement Wall_" not "_8 in. Normalweight Concrete Floor_".

The "**Construction Sets**" for Medium Office has both _Exterior Floor Construction Type_ and _Ground Contact Floor Construction_ Type specified but not clear at this moment how the "_6 in insulated floor construction_" is picked, so it is not clear if a new construction should be inserted in the "**Constructions**" tab to distinguish from the existing "_Typical Insulated Carpeted 6in Slab Floor_" and "_Typical Insulated Carpeted 8in Slab Floor_" in that tab.  

A temporal solution was taken: in the in the "**Constructions**" tab, the "_6 in. Normalweight Concrete Floor_" to "_8 in. Normalweight Concrete Floor_" for material layer 2 defined in column F for the construction of **Typical Insulated Carpeted 6in Slab Floor**

Although the observed differences were gone with this temporal solution, a better solution is needed to avoid the confusion of a "**Typical Insulated Carpeted 6in Slab Floor**" consists of a 8 in insulation layer.  

Need to figure out the best place (the google spreadsheet, which tab or the ruby script, which one) the change should be made to not break the other scripts yet solve this issue.

**Comment by lymereJ** [comment]
The prototypes now use the F-factor modeling approach so this doesn't apply anymore.
