### ISSUE TITLE
Mid-Rise MURB Space Function

### ISSUE THREAD

**Issue by mlubun** [NREL/openstudio-standards#213]
NECB 2011 sets a system 6 for an office in a building greater than 2 stories.   The mid-rise apartment is 4 stories and has a ground floor office, so a VAV system (System 6) is set, which also defines a chiller, cooling tower and a boiler.   The "office space function" should be set to "conference/meeting/multipurpose" which will define a system 3 (PSZ) for buildings 4 stories and less, which is consistent with the mid-rise MURB

**Comment by phylroy** [comment]
Will change this to the new space function.

**Comment by phylroy** [comment]
Attached is file with changes.
[final.zip](https://github.com/NREL/openstudio-standards/files/903917/final.zip)

**Comment by phylroy** [comment]
Mike Confirmed complete
