### ISSUE TITLE
Mismatched Roof Relectance in Medium Office

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#214]
Differences were found in the roof Reflectance between the idf models and the os models for Medium Office. 

The roof construction of both sets of models consist of three layers, a "Roof Membrane" layer, a "_Roof Insulation_" layer and a "_Metal Roof Surface_" layer. 

There are two issues in assigning _Solar Absorptance_ to the "_Roof Membrane_" layer.

In the "**Materials**" tab of the google spreadsheet, the S_olar Absorptance_ for "_Roof Membrane_" material is 0.77 but should be 0.7 (column F).  This material will be used for construction in CZ 4 to 8.
There is another "_Roof Membrane - Highly Reflective_" material in the "**Materials**" tab which has a Solar Absorptance of 0.45 to be used for construction in CZ 1 to 3.

In the "**Constructions**" tab, there are two type of roof defined, i.e., "_Typical IEAD Roof_" and "_Typical IEAD Roof - Highly Reflective_", which use material "_Roof Membrane_" or material "_Roof Membrane - Highly Reflective"_, respectively.
The "_Typical IEAD Roof - Highly Reflective_" construction should be used for CZ 1-3 and "_Typical IEAD Roof_" used for CZ 4-8.  However, in the "**Construction Properties**" tab, the construction (col G) for non-residential, exterior roof at Climate Zone 3 of 90.1-2013 is "_Typical IEAD Roof_" instead of "_Typical IEAD Roof - Highly Reflective_" (col G).

So two corrections were made: (1) "**Materials**" tab: changed the solar absorptance from 0.77 to 0.7 for "_Roof Membrane_" material (Col J of "**Materials**" tab) and (2) "**Construction Properties**" tab: changed construction type (col G) for 90.1-2013 (col A), non-residential (col F), ExteriorRoof (col D) at CZ 3 (col B) from "_Typical IEAD Roof_" to "_Typical IEAD Roof - Highly Reflective_". 

There are other minor differences in the materials: (1) there is a small difference in the density of the "_Roof Membrane_" material (1120 kg/m3 in the idf model and 1121.29 kg/m3 in the os model). (2) the roughness of the roof insulation material is "_MediumSmooth_" in the idf model but is "_Smooth_" in the os model.

**Comment by lymereJ** [comment]
These changes are already in the JSON files.
