### ISSUE TITLE
Potential Issues in the handling ceiling in the Medium Office

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#216]
This is an issue not directly based on differences from the tests.  Instead it was found when working on envelop components.

Different "**Outside Boundary Condition**" methods are used in the "BuildingSurface:Detailed" object.  Specifically _Zone_ is used in the idf model and _Surface_ is used in the os model.  

The idf models use **"DropCeiling**" construction which consists of the solo material of "_AC02 Acoustic Ceiling"_.  In the os models, a ceiling construction "_Typical Interior Ceiling_" is defined and used for ceiling and this ceiling construction is the same construction as " _Typical Interior Floor_" construction but with the materials/layers in a reverse order.  

When the "_Surface_" method is used for the outside boundary condition, surfaces need to be specified explicitly for the adjacent zone pairs.  For the plenum zones in the Medium Office, the ceiling surface of a plenum zone pairs with the floor surface of the thermal zone above, these two surfaces share the same construction but needs to be specified in two separate constructions with reversed order of materials/layers.  So it is all-right to use the specified "_Typical Interior Ceiling_" which is the revered ordered of "_Typical Interior Floor_" for the plenum ceiling.  However, the floor surface of a plenum zone refers the drop ceiling surface of the thermal zone below it and there is no drop ceiling construction defined and referred in current os models.  

In the Google Spreadsheet, "_acoustic ceiling_" material has been defined in the "**Materials**" tab, but there is only one ceiling surface type "_Typical Interior Ceiling_" defined in the "**Constructions**" tab, which has the revered order of materials/layers as the "_Typical Interior Floor_".  This is the one used for the ceiling of the plenum zones.  A different interior ceiling construction should be defined in the **Constructions** tab which will have one single "_acoustic ceiling_" material layer.  This new ceiling construction will be used as the ceiling construction of the thermal zones and the floor construction of the plenum zones.  

In order to use the newly defined acoustic ceiling construct, the "**Construction_Sets**" tab needs to be modified to have columns for the newly defined drop ceiling construction which will be used for the ceiling of the thermal zones and the floor of the plenums.  Currently, there are "_Ground Contact Ceiling Standards Construction Type_" and "_Ground Contact Ceiling Building Category_" columns in the "**Construction_Sets**" tab.  I am not sure about their usage.  But the new drop ceiling construction may be defined similarly.

There is no ceiling surface type (col D) in "**Construction Properties**" tab.  At this moment I am not sure what changes are needed in this tab as well as in pertinent ruby scripts in order to handle the two types of ceiling constructions.

**Comment by lymereJ** [comment]
These changes have already been addressed.
