### ISSUE TITLE
WeatherData .xls update for NECB 2011 to reflect MUA and PSZ references and add reference servcice water fuel

### ISSUE THREAD

**Issue by mlubun** [NREL/openstudio-standards#218]
See attached the weatherdata1.xls for BTAP

I have match the MUA (sys 4) fuel and the PSZ ( sys 3) fuel as we use PSZ to model MUA.

I have added a column on service water fuel to avoid natural gas water heaters in the far north.   They are electric now.   Please check the last column in the .xls  as I got the name wrong

Also I fixed the HDD for Resolute.

[WeatherData1.xlsx](https://github.com/NREL/openstudio-standards/files/900287/WeatherData1.xlsx)

**Comment by phylroy** [comment]
reference #174

**Comment by jblake59** [comment]
I am working on using Mike's new column of data added to the WeatherData1 hash for the service water heating fuel type (swh_fueltype.) This data is currently read in the function add_hvac(...) (in file Prototype.Model.hvac.rb) but the service water heating fuel type is not needed until the add_swh(...) function is called. For now, I'll implement the brute force solution of calling for the WeatherData1 values again in add_swh(...) even though only one data item is used.

**Comment by phylroy** [comment]
fixed and complete
