### ISSUE TITLE
Add/Modify information NECB-QAQC json output

### ISSUE THREAD

**Issue by padmassun** [NREL/openstudio-standards#219]
### **Information to be added:**

1. Add heating coils capacity to 
````
qaqc["air_loops"]["heating_coils"] > ["coil_heating_gas"], ["coil_heating_electric"], and ["coil_heating_water"]
````

2. Add fan power to 
````
qaqc["air_loops"]["supply_fan"] > ["fan_power"]
````
3. Add checks to determine correct economizer usage according to §5.2.2.7 of NECB 2011 [excel-AQ-AR]
4. Perform HRV calculation as per NECB 2011 §5.2.10.1 while assuming Supply Air less infiltration amount is exhausted [excel-AS]
5. Determine if HRV is required and is installed as per calculations done for  §5.2.10.1 [excel-AT-AU]
6. Determine NECB supply fan capacity as per §5.2.3.3 and [table 5.2.12.1 - NECB Clg COP] [excel-Y]
7. Remove Sanity check for undefined spaces and plenums
8. Calculate pump power in hp and compare it to theoretical values and check if it the value lies within ±20% of theoretical value [excel-Y]

### **Information to be moved:**

1. move breathing zone outdoor airflow and convert units from m3/s to L/s
````
qaqc["spaces"]["breathing_zone_outdoor_airflow_vbz"] to qaqc["air_loops"] > ["breathing_zone_outdoor_airflow_vbz"]
````

**Comment by padmassun** [comment]
@mlubun  @phylroy

**Comment by mlubun** [comment]
Add fan power check:
1.6 * airflow in L/sec for PSZ systems
2.65 * airflow in L/sec for VAV systems
Calculated and entered values should be within 10 L/sec
