### ISSUE TITLE
Need to make lighting and ventilation fan powers of elevators in Medium Office code dependent

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#220]
It was found that the elevator lighting power and elevator ventilation fan power (as well as the fraction radiant) differ between the IDF and OS models.  The elevator lighting and ventilation fan powers are standard dependent.  The add_elevator in prototype.hvac_systems.rb need to be modified to handle such a standard-dependency.   This might affect all prototypes with elevators.

**Comment by lymereJ** [comment]
This will be captured in the upcoming data refactoring.
