### ISSUE TITLE
A schedule difference identified in equipment schedule in Medium Office

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#221]
The schedules in the Medium Office models between IDF and OS models were compared and a difference was identified in the Sunday equipment schedule.  Changes have been made on Sunday Equipment Schedule of "OfficeMedium BLDG_EQUIP_SCH_2013" in the google standards spreadsheet.  Basically the values from 19:00-24:00 was changed from 0.23813625 to 0.237553806.

**Comment by lymereJ** [comment]
This change has already been implemented in the JSON files.
