### ISSUE TITLE
Infiltration schedules for Plenum zones don't allign with DOE prototype model

### ISSUE THREAD

**Issue by yanchenpnnl** [NREL/openstudio-standards#222]
Infiltration schedule for the three plenum zones (i.e., FirstFloor_Plenum_Infiltration, MidFloor_Plenum Infiltration, TopFloor_Plenum Infiltration) are using the "Always On Discrete" schedule.  This mismatches with the DOE prototype model.  It needs to be changed to "OfficeMedium INFIL_SCH_PNNL" schedule.   

The issue is likely caused by that the space type mapping definition in Prototype.medium_office.rb doesn't include the plenum zones.  So the plenum zones are assigned to a default schedule. 

(\lib\openstudio-standards\prototypes\Prototype.medium_office.rb)

`module MediumOffice
  def self.define_space_type_map(building_type, template, climate_zone)
    space_type_map = nil
    space_type_map = case template
    when 'NECB 2011'
      {
        '- undefined -' => ['FirstFloor_Plenum', 'TopFloor_Plenum', 'MidFloor_Plenum'],
        'Office - open plan' => ['Core_bottom', 'Core_mid', 'Core_top', 'Perimeter_bot_ZN_1', 'Perimeter_bot_ZN_2', 'Perimeter_bot_ZN_3', 'Perimeter_bot_ZN_4', 'Perimeter_mid_ZN_1', 'Perimeter_mid_ZN_2', 'Perimeter_mid_ZN_3', 'Perimeter_mid_ZN_4', 'Perimeter_top_ZN_1', 'Perimeter_top_ZN_2', 'Perimeter_top_ZN_3', 'Perimeter_top_ZN_4']
      }
    else
      {
        'WholeBuilding - Md Office' => ['Perimeter_bot_ZN_1', 'Perimeter_bot_ZN_2', 'Perimeter_bot_ZN_3', 'Perimeter_bot_ZN_4', 'Core_bottom', 'Perimeter_mid_ZN_1', 'Perimeter_mid_ZN_2', 'Perimeter_mid_ZN_3', 'Perimeter_mid_ZN_4', 'Core_mid', 'Perimeter_top_ZN_1', 'Perimeter_top_ZN_2', 'Perimeter_top_ZN_3', 'Perimeter_top_ZN_4', 'Core_top']
      }
                     end
    return space_type_map
  end`

In the Google doc, "OpenStudio_Standards", the data in the tab "Space Type" will need to be updated as well.

**Comment by lymereJ** [comment]
This issue has been addressed.
