### ISSUE TITLE
Redundant space types for Outpatient

### ISSUE THREAD

**Issue by padmassun** [NREL/openstudio-standards#223]
There are 2 pairs of redundant space types present in the generated osm file for the outpatient (generated by test_necb_bldg_outpatient.rb.
1) "*Office - enclosed*" and "*Office - enclosed - occsens*"
2) "*Storage area*" and "*Storage area - occsens*"

@mlubun and @jblake59 Are these space types supposed to be the same?

**Comment by mlubun** [comment]
The outpatient "Office - enclosed" should be "Office -enclosed - occsens" and "Storage area" should be "Storage area - occsens"    This is a space definition error on my part.

**Comment by padmassun** [comment]
UPDATE:
@jblake59 said
> Nobody should manually assign the “.. – occsens” space type since it is done in code based on the area of each space.

So, no changes will be made. But @jblake59 still has to confirm weather the occupancy sensors works correctly or not.

**Comment by jblake59** [comment]
This is a bug that I'm working on fixing.

**Comment by jblake59** [comment]
Fixed.
