### ISSUE TITLE
Oupatient System Type Issue

### ISSUE THREAD

**Issue by mlubun** [NREL/openstudio-standards#225]
In NECB 2011 Table 8.4.4.9A defines the system reference type per space types.   The outpatient spaces 'Floor 1 MRI Control Room', 'Floor 1 MRI Room', 'Floor 2 X-Ray' were assigned space type ‘Hospital - radiology/imaging’ for lighting, plug loads, occupancy, schedules, ....
According to Table 8.4.4.9A, the ‘Hospital - radiology/imaging’ space type would more closely align with hospital laboratories in the Critical care / space of table 8.4.4.9A than the General space type which includes offices, health care clinic, libraries, retail.   Therefore these 3 spaces which are defined as separate zones would then be served with a PSZ (Sys 3), rather than VAV (Sys 6).

**Comment by padmassun** [comment]
Related to #224
