### ISSUE TITLE
QAQC for Lighting power density fails incorrectly for spaces with Reduced Lighting power density

### ISSUE THREAD

**Issue by padmassun** [NREL/openstudio-standards#227]
QAQC's check needs to be modified for Lighting power density for spaces with Occupancy sensors. The QAQC does not apply a factor of 0.9 for 
1) space_type of 'Storage area' with floor Area < 100 m<sup>2</sup>
2) space_type of 'Storage area - refrigerated' with floor Area < 100 m<sup>2</sup>
3) space_type of 'Office - enclosed' with floor Area < 25 m<sup>2</sup>
4) space_type of ["Classroom/lecture/training", "Conf./meet./multi-purpose", "Lounge/recreation",
"Conf./meet./multi-purpose", "Washroom-sch-A", "Washroom-sch-B", "Washroom-sch-C", "Washroom-sch-D", "Washroom-sch-E", "Washroom-sch-F", "Washroom-sch-G", "Washroom-sch-H", "Washroom-sch-I", "Dress./fitt. - performance arts", "Locker room", "Retail - dressing/fitting"]

**Comment by jblake59** [comment]
Yes it does but I'm testing further in light of issue #223. This problem was originally fixed in issue #164 .

**Comment by jblake59** [comment]
@padmassun : Can you provide specific building type failure? I'm testing with outpatie nt now and seems to be (mostly) working. Still ongoing work.

**Comment by padmassun** [comment]
UPDATE:
@jblake59  I had a discussion with @mlubun and compared your LPD code, and we came across some space types that are missing a LPD factor of 0.9

1) Only "Locker room" was found in your code. There was no "Locker room-sch-A", "Locker room-sch-B" ... "Locker room-sch-I"
2) "Office - open plan" is not included and has to be checked if the area is < 25 m<sup>2</sup>
3) @mlubun considers "Hospital - medical supply" as a supply space, so it has to be checked if the area is < 100 m<sup>2</sup>

**Comment by jblake59** [comment]
@padmassun : In discussions with @mlubun for original issue #164 decided not to ste for "Office - open plan". But no problem changing.

**Comment by padmassun** [comment]
@jblake59 It is OK to leave "Office - open plan" off the list.

**Comment by padmassun** [comment]
https://github.com/NREL/openstudio-standards/commit/394798b31ec3f8dfd10b6fa803a81ee1e2936245

**Comment by jblake59** [comment]
@phylroy: All fixed. This issue can be closed if Circleci passes.

**Comment by jblake59** [comment]
CircleCI passed all tests.
