### ISSUE TITLE
Fan control type in VAV systems

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#234]
There are idf differences in the fan power control between the IDF and the OD models.

Single zone VAV fan control is handled through EMS program in the IDF models.  The OS model will enable the EMS program on the single zone VAV fan control. 

For multizone VAV system in the OS models, it is handled through "part_load_fan_power_limitation()" of "Standards.FanVariableVolume.rb" and "apply_standard_controls()" of "Standards.AirLoopHVAC.rb".  The following changes have been made.
(1) the threshold of the motor or cooling capacity are modified in "part_load_fan_power_limitation()" to reflect 90.1-2013.
(2) Two fan performance curves which are used in the prototype models are added in "Standards.FanVariableVolume.rb" with proper fan power minimum flow fractions.
(3) the assumption of no systems having DDC control are changed to all mulitzone VAV systems having DDC control for all years of 90.1 prototypes.  plr_req alone determines which fan performance curve to use.

**Comment by lymereJ** [comment]
Single zone system are not modeled through an EMS program anymore.
