### ISSUE TITLE
Put daylighting control illuminance setpoints in google standards spreadsheet.

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#235]
This is related issues #232.

Currently a constant default illuminance setpoint is hard coded in "Standards.Space.rb". The illuminance setpoints are building type and space type dependent.  It is decided to put them in the google standards spreadsheet and use them on the fly.  The 90.1-2010|2013 illuminance setpoints of applicable prototypes have been put in tab "Space Type" of the google standards spreadsheet.  In addition, for the three office prototypes, the daylightable PSA and SSA fractions of the perimeter area based non-geometrical related assumptions are also included in the "Space Type" tab of the Google Standards spreadsheets.  They will be applied on the geometrical fractions of PSA and SSA of the perimeter area to derive the fraction of zone controlled by the sensors.

Need to modify "add_daylighting_controls()" of "Standards.Space.rb" to make the changes work.

**Comment by lymereJ** [comment]
Setpoints are now stored in the data.
