### ISSUE TITLE
Add Yellowknife

### ISSUE THREAD

**Issue by jblake59** [NREL/openstudio-standards#236]
We have a CWEC file for Yellowknife but do not process it due to missing data.  Yellowknife is the only climate zone 8 city for **costing**.  For energy sims, we are forced use another climate zone 8 weather file (e.g., Churchill, Resolute, Inuvik, Schefferville) and apply Yellowknife costing to it.   It would be better to have a Yellowknife weather file!

**Comment by padmassun** [comment]
Please See:

**Comment by jblake59** [comment]
Closed because Padmassun added Yellowknife in referenced commits shown above. A separate issue with the costing data missing was resolved by Mike and Kamel (couldn't find an issue entry for).

**Comment by jblake59** [comment]
From @phylroy : Looks Like Yellowknife is still a problem with Gas meters - no gas available in Yellowknife!.  Could you look into this? I'll ask Tyson to remove Yellowknife from the runs for now.

**Comment by jblake59** [comment]
Crash happens when apply the "Utility Tariffs Model Setup" measure. Get the following error:
> ...
> Processing EnergyPlus Measures.
> Applying UtilityTariffsModelSetup
>   Result: Fail
>   Error: 
>  Error in lookup of /tmp/OpenStudioApp.BC1186/resources/measures/BTAPUtilityTariffs/resources/utility_tariffs.csv 
>  No matches found for {"meter_name"=>"Gas", "city"=>"Yellowknife"}
> ...

**Notes:**
1. There is no gas used anywhere in the model so don't understand why it is checked!
2. Sometimes get a similar error but for "Electricity" when there is an electricity record for Yellowknife in utility_tariffs.csv!

Something "fishy" going on!!

**Comment by jblake59** [comment]
Committed a fix to Weather.model.rb listing for Yellowknife boiler fuel. Chnaged from FuelOil#1 to FuelOil#2 to match data in utilty_tariffs.csv

**Comment by jblake59** [comment]
Problem caused by three meter blocks created in OSM file when there should be only one! The meter in bold below is the only correct one:

> OS:Output:Meter,
>   {abc5d571-df7f-47b1-bf8b-892a6dadede3}, !- Handle
>   **Gas**:Facility,                           !- Name
>   Hourly,                                 !- Reporting Frequency
>   True,                                   !- Meter File Only
>   False;                                  !- Cumulative

> OS:Output:Meter,
>   {15699204-c979-4451-b40c-3b532d8c0da9}, !- Handle
>   **ElectricityNet**:Facility,                !- Name
>   Hourly,                                 !- Reporting Frequency
>   True,                                   !- Meter File Only
>   False;                                  !- Cumulative

**OS:Output:Meter,
  {d446ed18-52cc-487c-bf58-c78a8edaa642}, !- Handle
  Electricity:Facility,                   !- Name
  Hourly,                                 !- Reporting Frequency
  True,                                   !- Meter File Only
  False;                                  !- Cumulative**

**Comment by khaddad** [comment]
The utility tariff resource file needs data for all fuel types for every location even though the fuel is not used in a particular location ('Gas' in 'Yellowknife'). Added a row for 'Ga's for 'Yellowknife'.
