### ISSUE TITLE
space_type.apply_internal_loads returns nil in some cases

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#238]
https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.SpaceType.rb#L80

Normal behavior is to return true or false, but found that for Large Office Data Center space types it returns nil instead. Maybe because they don't have space infiltration? But could be something else.

I fixed issue in measure by checking specifically for false, so no rush for this fix. I also plan to add space infiltration to the data center space types, but will hold off for a while, not in a hurry to do that.

**Comment by jiangithub** [comment]
The data center in the DOE Large Office prototype is a space in the basement and it has very high electric equipment load density. There should not be any infiltration and heating load.

**Comment by DavidGoldwasser** [comment]
@asparke2 can confirm this, but this shouldn't affect the prototype building, it's in the "Infiltration per Exterior Area (ft^3/min*ft^2 ext)" column of the space types tab in Google Doc spreadsheet that is only used when users apply internal loads through `space_type.apply_internal_loads`

If I user happens to apply this to a space type that doesn't have any interior exposure, then it won't have any infiltration. As a related note there is also the option of a "Infiltration per Exterior Wall Area (ft^3/min*ft^2 ext)" input for infiltration, but that isn't used very much.
