### ISSUE TITLE
Initial minimum damper position for multizone VAV systems

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#241]
For multizone VAV systems with electric or hydronic reheat, the minimum damper position (MDP) is specified in Standards.AirTerminalSingleDuctVAVReheat.rb and Prototype.AirTerminalSingleDuctVAVReheat.rb. The method calculates the MPD based on zone ventilation requirement and zone design load and uses an initial MPD as a starting point for the MDP calculation. The general rule for initial MDP in the OS prototype was resolved in another issue. The prototypes and spaces (critical zones with high occupancy density and low design thermal load) with exceptions in the DOE Prototype idf models are currently not used in the current OS prototype methods.  

One solution is to hard code the exceptions in the Standards.AirTerminalSingleDuctVAVReheat.rb and/or Prototype.AirTerminalSingleDuctVAVReheat.rb. 

PNNL is working with E+ development team to examine the native E+ capability to do the MDP adjustment automatically. If that is successful, it’ll be a better way to go for the future.

**Comment by lymereJ** [comment]
Fixed by #776.
