### ISSUE TITLE
Autosizing of cooling tower UA failed for tower COOLING TOWER SINGLE SPEED 1

### ISSUE THREAD

**Issue by padmassun** [NREL/openstudio-standards#243]
The following buildings had this error:
`NECB 2011-SmallHotel-NECB HDD Method-CAN_NU_Resolute.719240_CWEC.epw`
`NECB 2011-LargeHotel-NECB HDD Method-CAN_NU_Resolute.719240_CWEC.epw`

#### Eplusout error log:
```
** Severe  ** Bad starting values for UA
   **  Fatal  ** Autosizing of cooling tower UA failed for tower COOLING TOWER SINGLE SPEED 1
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=2
   ..... Last severe error=Bad starting values for UA
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   *************
   ************* ===== Final Error Summary =====
   ************* The following error categories occurred.  Consider correcting or noting.
   ************* Nominally Unused Constructions
   ************* ..The nominally unused constructions warning is provided to alert you to potential conditions that can cause
   ************* ..extra time during simulation. Each construction is calculated by the algorithm indicated in the HeatBalanceAlgorithm
   ************* ..object. You may remove the constructions indicated (when you use the DisplayExtraWarnings option).
   *************
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 387 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 457 Warning; 2 Severe Errors; Elapsed Time=00hr 00min  5.03sec
```

More building and weather file pairs with this error will be posted by the end of today.

**Comment by jblake59** [comment]
This problem only happens with the Resolute weather file (very extreme North). The Inuvik, NT file (far North in Northwest Territory) runs fine. Both the large and small hotels have a mixture of packaged single zones systems (DX cooling) and a single VAV Reheat (with chilled water cooling). The cooling tower sizing using UA at design air flow rate appears to be the issue.

**Comment by jblake59** [comment]
**Zone Cooling Sizing Information from E+ for SP-EXERCISECENTERFLR1 SYS-6 FLR-1 SCH-B HPLCMT-SOUTH ZN (this is one of the two zones on the VAV Reheat System whose cooling tower fails):** 
Calc Des load = 1015 W 
User Des load = 1117 W
Calc Des air flow rate = 7.58698E-002 m3/s (161 CFM), 
User Des air flow rate = 0.14246 (302 CFM)
RESOLUTE ANN CLG .4% CONDNS DB=>MWB:  7/21 13:15:00 
**Temperature at Peak = 10.62375 C** 
Humidity Ratio at Peak = 5.31187E-003 kgWater/kgDryAir
Floor Area = 32.60897 m2
Num Occupants = 6.52158
Calc Outdoor Air Flow Rate = 0.14246 m3/s

So this zone is getting 0.14246 m3/s of outdoor air (100%) at 10.6 C at the cooling coil so the coil sees a very small load (~570 W to deliver 7 C air).  This creates an issue with coil sizing on the chilled water loop and cooling tower sizing on the condenser water loop.

**Recommendation**: Don't include the Resolute weather file in the tests for small and large hotels!

**Comment by padmassun** [comment]
Resolute weather file will not be included in any runs, because @phylroy wants the run to be consistent.

**Comment by tabuimara** [comment]
I had the same issue with medium office in Toronto , but by increasing the fan power capacity I was able to run the simulation and the error disappeared
