### ISSUE TITLE
apply_prm_baseline_supply_temperatures will always return false

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#247]
This is mostly a design issue from OpenStudio, but this line is guilty as well: https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.ThermalZone.rb#L1217

setZoneHeatingDesignSupplyAirTemperature returns a void and that's why I'm saying it's an OpenStudio design issue, I think it should be a bool. 

So later when you do `if htg_success && clg_success` you'll always end up returning `false`.

This related to https://github.com/NREL/OpenStudio/issues/2620

**Comment by mdahlhausen** [comment]
Fixed a while ago in OpenStudio with https://github.com/NREL/OpenStudio/issues/2620.  This return on the openstudio-standards method isn't used yet, so I'm not going to change it to handle the void returns for old versions of OpenStudio.
