### ISSUE TITLE
Geometry Problems for Hospital

### ISSUE THREAD

**Issue by phylroy** [NREL/openstudio-standards#253]
I'm reviewing the geometry of the hospital file here (https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/data/geometry/Geometry.hospital.osm) at revision b882aba

I've noticed 4 issues with the geometry that cause errors in both OS and E+

1. If you try to load the osm file programatically. You will get this error indicating surfaces with sides <3.....
```bash
[openstudio.model.Model] <0> The run completed but had the following severe errors: GetSurfaceData: There are 1 degenerate surfaces; Degenerate surfaces are those with number of sides < 3.  These surfaces should be deleted.  For explicit details on each problem surface, use Output:Diagnostics,DisplayExtraWarnings;
```
2. If you load the file in Sketchup to will get these errors. 
![image](https://user-images.githubusercontent.com/5103270/27357801-ab614cd6-55e1-11e7-9ee9-ea97dbb00363.png)

3. If you look at the surfaces for  "Corridor_Flr_2_Wall_North" it is not intersected with the surfaces of the adjacent spaces. 
![image](https://user-images.githubusercontent.com/5103270/27358031-b8f487cc-55e2-11e7-877a-b0a6c2a12ea2.png)
There should be at least three surfaces on the side of the corridor.
![image](https://user-images.githubusercontent.com/5103270/27358081-01fd4878-55e3-11e7-9beb-21d3eb9c898a.png)

4. There are at least 1 surface missing from the model.  There may be more hidden. 
![image](https://user-images.githubusercontent.com/5103270/27358201-7354774e-55e3-11e7-9c56-ec03955cd354.png)

I do understand that some of these surfaces are adiabatic...but this will still cause problems in logic for OpenStudio and E+ it the surfaces are not intersected.

**Comment by padmassun** [comment]
I have added a new geometry file for the hospital. See 47252763df700d5fac194ac98c2a9f69428edb15

**Comment by padmassun** [comment]
regarding `GetSurfaceData` issues, there was only a warning for hospital
```
```   ** Warning ** GetSurfaceData: InterZone Surface Areas do not match as expected and might not satisfy conservation of energy:
   **   ~~~   ** ...use Output:Diagnostics,DisplayExtraWarnings; to show more details on individual mismatches.
   ** Warning ** GetSurfaceData: WindowProperty:ShadingControl: "SHADING CONTROL 1" is not referenced by any window.```
```

I will look into ShadingControl items

**Comment by padmassun** [comment]
The problems with the Hospital geometry issues are solved. There are some sketchup bugs,(https://github.com/NREL/OpenStudio/issues/2681), But it will not have an impact on the run. The geometry of this hospital still has to be reviewed.

**Comment by padmassun** [comment]
The geometry of this hospital still has to be reviewed.
