### ISSUE TITLE
ScheduleRuleset.annual_min_max_value can return values that are never hit throughout the year

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#257]
It looks through the default profile and the rules and finds the min and max values. It doesn't validate that the default profile or specific results are used in 8760 simulation. I ran across case where default profile wasn't used and this method returned misleading values. Could be nice to make it more robust and have it check if profile is used before including values from it in min and max values.

**Comment by mdahlhausen** [comment]
The way to fix this is to check that rule indices are applicable in the schedule_ruleset_get_min_max() method
