### ISSUE TITLE
applySizingValues method undefined for HeatExchangerFluidToFluid

### ISSUE THREAD

**Issue by brianlball** [NREL/openstudio-standards#260]
The method applySizingValues crashes if there is a heatExchangerFluidToFluid in the model.

______________________________________________________________________________________________________
irb(main):019:0> model.applySizingValues
NoMethodError: undefined method `applySizingValues' for #<OpenStudio::Model::Hea
tExchangerFluidToFluid:0x000000111c9d30>
       from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/openstudio-standards-0.1.13/
lib/openstudio-standards/hvac_sizing/Siz.Model.rb:200:in `block in applySizingVa
lues'
       from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/openstudio-standards-0.1.13/
lib/openstudio-standards/hvac_sizing/Siz.Model.rb:200:in `each'
       from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/openstudio-standards-0.1.13/
lib/openstudio-standards/hvac_sizing/Siz.Model.rb:200:in `applySizingValues'
       from (irb):19

**Comment by asparke2** [comment]
Fixed in OpenStudio core C++ as of 2.4.0.  See [this line].(https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/HeatExchangerAirToAirSensibleAndLatent.cpp#L733)
