### ISSUE TITLE
create_prm_baseline_building should remove existing daylight controls

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#274]
This: https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.Model.rb#L169

should be 
>added = space.add_daylighting_controls(template, __true__, false)

to remove any daylight controls in the proposed model beyond those required by code.

**Comment by MatthewSteen** [comment]
Now here...

https://github.com/NREL/openstudio-standards/blob/5fe0f175d9156c567dfe83a4c4c9948bb65e616c/lib/openstudio-standards/standards/Standards.Model.rb#L1877

**Comment by mdahlhausen** [comment]
Fixed with #1303
