### ISSUE TITLE
issues with daylighting control in Retail Standalone and Small Office

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#284]
(1) daylighting control is missing for Core Retail of Retail Standalone
    (2) sensor control fractions are not CZ dependent. 
    
    Changes were made in "Standards.Space.rb" to 
    (i) add daylighting control with two sensors for Core Retail of Standalone Retail and 
    (ii) make sensor control fraction CZ dependent for Small Office and Retail Standalone.  
    Currently hard coded and better way should be used.

**Comment by asparke2** [comment]
Fixed in https://github.com/NREL/openstudio-standards/pull/448
