### ISSUE TITLE
UnitHeater fan in Front Entry of Standalone

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#286]
Unit heater fan was currently defined as a small fan (together with exhaust fan, PTAC fan and PTHP fans),  which has motor and fan impeller efficiency based on 0.5 HP.

Removed unitheater fan from the list of the small fan and treated as autosized.

**Comment by asparke2** [comment]
Fixed in https://github.com/NREL/openstudio-standards/pull/448
