### ISSUE TITLE
WaterHeater related issues

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#287]
(1) missing the use of zone where the water heater is located: 

added a column in "prototype inputs" of google doc to specify the zone name where water heaters are located. Use the zone name if it is specified in prototype inputs of google doc
    
    (2) PNNL prototypes have prototype dependent "off cycle parasitic heat fraction to tank":

added two columns in "prototype inputs" of google doc to specify the off cycle parasitic heat fraction 
      for both main water heater and all other water heater.
    made change in “Prototype.hvac_systems.rb” and “Prototype.models.rb” and “Standards.WaterHeaterMixed.rb”  to assign values if there is a specified off cycle parasitic heat fraction.
    
    (3) calculation of "loss coefficients to ambient temperature" differ between OS and PNNL models:
        
Changes were made on "Standards.WaterHeaterMixed.rb", "Prototype.Model.rb", "Prototype.Model.swh.rb" to use PNNL model values to overwrite the OS calculations.

**Comment by asparke2** [comment]
Fixed in https://github.com/NREL/openstudio-standards/pull/448
