### ISSUE TITLE
Perimeter_ZN_1_wall_south_door should be a glassdoor in Small Office

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#293]
Changed opaque door to glassdoor for Perimeter_ZN_1_wall_south_door in Small Office: the change includes assigning glassdoor in "geometry.small_office.osm" and associating a window object with the glass door in "Construction Sets" of google doc.

**Comment by asparke2** [comment]
Fixed in https://github.com/NREL/openstudio-standards/pull/448
