### ISSUE TITLE
issues with heating and cooling cop calculation

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#294]
(1)  expanded the code requirement tabs e.g., "Heat Pumps","Heat Pumps Heating", to account for code effect date.
    (2) added seer to cop method for cooling and heating cop calculation when supply fan exist.
    (3) modified eer to cop method for cooling and heating cop calculation.

**Comment by asparke2** [comment]
Fixed in https://github.com/NREL/openstudio-standards/pull/448
