### ISSUE TITLE
correcting motorized damper schedule

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#295]
(1) Currently motorized damper is always used except buildings less than 3 stories for CZ 1-3 or building with system OA < 300 cfm.  The latter was not implemented in the PNNL model so it is disabled.

    (2) Skipped modifying min OA schedule in the scripts if it has been already assigned in "prototype inputs" of google doc.

**Comment by asparke2** [comment]
Fixed in https://github.com/NREL/openstudio-standards/pull/448
