### ISSUE TITLE
Issue in attic zone surface construction of Small Office

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#296]
The current OS model has placed the insulation on the attic roof which should be placed between the attic and the conditioned zone. Changes have been made to fix the attic soffit construction.

**Comment by asparke2** [comment]
Fixed in https://github.com/NREL/openstudio-standards/pull/448

**Comment by asparke2** [comment]
Fixed in https://github.com/NREL/openstudio-standards/pull/448
