### ISSUE TITLE
Make building_type, climate_zone, and vintage consistent

### ISSUE THREAD

**Issue by asparke2** [NREL/openstudio-standards#30]
1. Maybe make these attributes of OpenStudio::Model::Model
2. Pick either vintage or template and make consistent

**Comment by macumber** [comment]
@asparke2 are you aware of these existing objects/attributes?

* Building::standardsBuildingType
* ClimateZones

I'm not sure if we have a vintage attribute, if we don't I think it would be appropriate to add to Building, what do you think?

@DavidGoldwasser FYI

**Comment by asparke2** [comment]
Going to standardize on one term for each of these things.

**Comment by asparke2** [comment]
closed by https://github.com/NREL/openstudio-standards/pull/103
