### ISSUE TITLE
model_add_prm_construction_set missing arguments

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/openstudio-standards#347]
The [model_add_prm_construction_set](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.Model.rb#L1617) method is missing most of the arguments used in the method (clim, building_type, spc_type, etc.).

Not sure if it needs to be deprecated since it doesn't appear to be used anywhere else in the library and the [model_add_construction_set](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.Model.rb#L2547) method appears to perform the same function.

**Comment by mdahlhausen** [comment]
Looks like this method was removed a while ago.
