### ISSUE TITLE
add check for zero capacity district cooling and heating

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/openstudio-standards#362]
It's common to use DistrictCooling or DistrictHeating objects with zero capacity for designs that have radiant systems that provide cooling *or* heating by connecting the radiant coils that don't exist in the design to a loop with zero capacity and pump power. 

In these cases, the standards creates a 90.1 baseline that also uses district energy. I think this could happen in the methods below and maybe others.

* [plant_loop_heating_fuels](https://github.com/NREL/openstudio-standards/blob/0a5905fbf8de6e28c1dbfa074543233aed85aed2/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb#L16)
* [plant_loop_cooling_fuels](https://github.com/NREL/openstudio-standards/blob/0a5905fbf8de6e28c1dbfa074543233aed85aed2/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb#L88)

**Comment by mdahlhausen** [comment]
This was added to OpenStudio in https://github.com/NREL/OpenStudio/pull/4799 and methods removed from openstudio-standards in https://github.com/NREL/openstudio-standards/pull/1582.
