### ISSUE TITLE
Create DEER Prototype Building ALPHA Version geometry has unenclosed spaces

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#393]
Inputs:
Health/Medical - Hospital: Packaged VAV System with Gas Boiler
DEER 2017
CEC T24-CEC5

![capture0](https://user-images.githubusercontent.com/39242689/42786330-aae02324-890a-11e8-83af-3d2281a04c02.PNG)
![capture1](https://user-images.githubusercontent.com/39242689/42786408-034bbf5a-890b-11e8-8cc0-baf9532b7e8e.PNG)

**Comment by asparke2** [comment]
Fixed in https://github.com/NREL/openstudio-standards/pull/463
