### ISSUE TITLE
Create DEER Prototype Building ALPHA Version roof does not enclose plenum

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#396]
Inputs:
Lodging - Hotel: Split or Packaged DX Unit with Heat Pump
DEER 2017
CEC T24-CEC5

Floor 3 of the model has multipliers applied to simulate all the middle floors, but the roof of the plenums for the multiplied floor has the same coordinates as the floor of the topmost explicitly specified floor.

`   ** Warning ** CalculateZoneVolume: The Zone="EL1 EAST PERIM PLNM (G.E6) ZN" is not fully enclosed.`

![capture0](https://user-images.githubusercontent.com/39242689/42788594-553bf834-8915-11e8-9835-43dc60ea8510.PNG)
![capture1](https://user-images.githubusercontent.com/39242689/42788595-5558c1bc-8915-11e8-8091-cdfadded1a36.PNG)

**Comment by mdahlhausen** [comment]
Fixed with [this pull request](https://github.com/NREL/openstudio-standards/pull/463)
