### ISSUE TITLE
Create DEER Prototype Building ALPHA Version zones unenclosed due to long surface edges

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#397]
Inputs:
Manufacturing Biotech: Built-Up VAV System with Electric Reheat
DEER 2017
CEC T24-CEC5

Energyplus is sometimes unable to correctly determine when very long surface edges, such as the top of a wall and joining roof, are coincident. This appears to be a problem for this model. Looks like extra points were added to the surfaces in the model so Energyplus would correctly determine that the surfaces are properly aligned, but Energyplus has also removed those points as collinear. To fix the problem, the extremely long surfaces will probably have to be split up into several surfaces with reduced length.

`   ** Warning ** GetSurfaceData: There are 48 coincident/collinear vertices; These have been deleted unless the deletion would bring the number of surface sides < 3.`

`   ** Warning ** CalculateZoneVolume: The Zone="EL1 NORTH PERIM PLNM (G.N14) ZN" is not fully enclosed. To be fully enclosed, each edge of a surface must also be an edge on one other surface.`

```
   **   ~~~   **   The surface    "EL1 NORTH WALL (G.N14.E9)" has an edge that is either not an edge on another surface or is an edge on three or more surfaces: 
   **   ~~~   **     Vertex start { 333.8932, 55.6412, 2.7432}
   **   ~~~   **     Vertex end   { 0.0000, 55.6412, 2.7432}
```

![capture](https://user-images.githubusercontent.com/39242689/42789382-ef871320-8919-11e8-9bc4-53773aa38627.PNG)

**Comment by mdahlhausen** [comment]
Fixed with [this pull request](https://github.com/NREL/openstudio-standards/pull/463)
