### ISSUE TITLE
Solution Exception: Honeybee_OpenstudioStandardsFile 

### ISSUE THREAD

**Issue by Elhamsoltani** [NREL/openstudio-standards#408]
Hello,
I hope all is well. I encountered a problem in my Grasshopper that I cannot do the simulations. It worked before but this is a new problem. Attached please find the screenshot for the error. I appreciate if could help me to solve this problem.

Thank you in advance for your consideration.

![openstudio](https://user-images.githubusercontent.com/41838288/43368245-2d71abe2-930f-11e8-994f-b35b432075b1.PNG)

**Comment by mdahlhausen** [comment]
This an issue with Honeybee, not openstudio-standards
