### ISSUE TITLE
"Create DOE Prototype Building" BCL measure Design Pump Head {Pa} field extremely low

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#444]
Running "Create DOE Prototype Building" BCL measure with parameters
QuickServiceRestaurant
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

The pump Pump:ConstantSpeed has 0.001 in the Design Pump Head {Pa} field, which is about 10^7 smaller than the default value of 179352 in a newly created Pump:ConstantSpeed object in the IDF editor. This manifests in the ERR file as

** Warning ** Check input. Pump nominal power or motor efficiency is set to 0, for pump=SERVICE WATER LOOP PUMP

Pump:ConstantSpeed,
    Service Water Loop Pump, !- Name
    0.001,                   !- Design Pump Head {Pa}

Pump:ConstantSpeed,
    Default Pump Values,                        !- Name
    179352,                  !- Design Pump Head {Pa}

**Comment by mdahlhausen** [comment]
Plant loops in EnergyPlus must include a pump, but municipal water system pressure is sufficient for many service hot water loops in reality.  openstudio-standards models this with a tiny design pump head to mimic the absence of a pump.
