### ISSUE TITLE
"Create DOE Prototype Building" BCL measure incorrect pairing of components

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#445]
Running "Create DOE Prototype Building" BCL measure with parameters
FullServiceRestaurant
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

A Coil:Cooling:DX:TwoSpeed object is paired with a Fan:ConstantVolume in the air loop, which shows in the ERR file as

** Warning ** CalcTwoSpeedDXCoilStandardRating: Did not find an appropriate fan associated with DX coil named = "DINING ZN PSZ-AC 2SPD DX AC CLG COIL 330KBTU/HR 10.0EER". Standard Ratings will not be calculated.

**Comment by lymereJ** [comment]
We're planning to update these models to use the Fan:SystemModel object.
