### ISSUE TITLE
"Create DOE Prototype Building" BCL measure missing roof

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#446]
Running "Create DOE Prototype Building" BCL measure with parameters
Hospital
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

One of the roofs has almost zero area, which is removed during the simulation.

![missing roof](https://user-images.githubusercontent.com/39242689/44691400-60cdca00-aa13-11e8-8596-1679b8a28fda.PNG)

BuildingSurface:Detailed,
    Office2_Mult5_Flr_5_Ceiling,  !- Name
    Roof,                    !- Surface Type
    Typical IEAD Roof - Highly Reflective R-20.83,  !- Construction Name
    Office2_Mult5_Flr_5 ZN,  !- Zone Name
    Outdoors,                !- Outside Boundary Condition
    ,                        !- Outside Boundary Condition Object
    SunExposed,              !- Sun Exposure
    WindExposed,             !- Wind Exposure
    ,                        !- View Factor to Ground
    ,                        !- Number of Vertices
    9.144,                   !- Vertex 1 X-coordinate {m}
    7.62,                    !- Vertex 1 Y-coordinate {m}
    21.3415,                 !- Vertex 1 Z-coordinate {m}
    9.144,                   !- Vertex 2 X-coordinate {m}
    7.622,                   !- Vertex 2 Y-coordinate {m}
    21.3415,                 !- Vertex 2 Z-coordinate {m}
    0,                       !- Vertex 3 X-coordinate {m}
    7.622,                   !- Vertex 3 Y-coordinate {m}
    21.3415,                 !- Vertex 3 Z-coordinate {m}
    0,                       !- Vertex 4 X-coordinate {m}
    7.62,                    !- Vertex 4 Y-coordinate {m}
    21.3415;                 !- Vertex 4 Z-coordinate {m}

** Severe  ** GetSurfaceData: There are 1 degenerate surfaces; Degenerate surfaces are those with number of sides < 3.
   **   ~~~   ** These surfaces should be deleted.
   **   ~~~   ** For explicit details on each problem surface, use Output:Diagnostics,DisplayExtraWarnings;

**Comment by mdahlhausen** [comment]
[Fixed with this commit](https://github.com/NREL/openstudio-standards/commit/84776cbc248894e182c6b6e4b7b515698aa72752)
