### ISSUE TITLE
Implementing PTHP standards

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#45]
I'd like to implement PTHP standards for the baseline automation. Just like PTAC, PTHP has a heating efficiency requirement that is dependent on capacity.

Looking at the OpenStudio Standards Google Spreadsheet, first I'm a bit confused of the distinction between "Heat Pumps Heating" and "Heat Pumps" tabs, but I'd suppose Heat Pumps is the cooling side of the HP, and the "Heat Pumps Heating" is the heating side?

Anyways, similarly to what has been done I'd propose something along the lines:

* Adding another subcategory called "PTHP" to the "Heat Pumps" tab

* Adding a subcategory "PTHP" to the "Heat Pumps Heating" tab, and two other columns "PTHP_COP_Coefficient_1" and `PTHP_COP_Coefficient_2`. 

What do you think?

**Comment by asparke2** [comment]
@jmarrec Yeah I think this approach is good.  I will implement.

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/commit/0eaf0d5fb82d57097bb8f0270fa7425af13318df
