### ISSUE TITLE
Create DEER Prototype Building ALPHA Version is unable to calculate the volume of a zone and 7 zones are considered unenclosed

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#455]
Inputs:
Education - Community College: Split or Packaged DX Unit with Heat Pump
DEER 2017
CEC T24-CEC5

   ** Severe  ** For zone: EL3 SW PERIM SPC (G.SW1) ZN it is not possible to calculate the volume from the surrounding surfaces so either provide the volume value or define all the surfaces to fully enclose the zone.
   ** Warning ** Indicated Zone Volume <= 0.0 for Zone=EL3 SW PERIM SPC (G.SW1) ZN
   **   ~~~   ** The calculated Zone Volume was=0.00
   **   ~~~   ** The simulation will continue with the Zone Volume set to 10.0 m3. 
   **   ~~~   ** ...use Output:Diagnostics,DisplayExtraWarnings; to show more details on individual zones.

   ** Warning ** CalculateZoneVolume: 7 zones are not fully enclosed. For more details use:  Output:Diagnostics,DisplayExtrawarnings;

**Comment by mdahlhausen** [comment]
Fixed with [this pull request](https://github.com/NREL/openstudio-standards/pull/463)
