### ISSUE TITLE
Create DEER Prototype Building ALPHA Version has a frost/freeze warning for Coil:Cooling:DX:SingleSpeed over 2000 times during simulation

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#456]
Inputs:
Education - Community College: Split or Packaged DX Unit with Heat Pump
DEER 2017
CEC T24-CEC5

** Warning ** CalcDoe2DXCoil: Coil:Cooling:DX:SingleSpeed="EL4 CORE SPC (T.C17) ZN EL4 SYS3 (PVVT) (T.C17) 1SPD DX HP CLG COIL" - Full load outlet temperature indicates a possibility of frost/freeze error continues. Outlet air temperature statistics follow:
**   ~~~   **   This error occurred 2358 total times;
**   ~~~   **   during Warmup 0 times;
**   ~~~   **   during Sizing 0 times.
**   ~~~   **   Max=1.998127  Min=-2.224089

**Comment by mdahlhausen** [comment]
This is typical of this object.
