### ISSUE TITLE
Feature Request: ChangeBuildingLocation BCL measure creates the Site:GroundTemperature:BuildingSurface

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#457]
The ChangeBuildingLocation BCL measure creates the Site:Location, Site:WaterMainsTemperature, and SizingPeriod:DesignDay objects in the model based on input epw and stat files. Missing when changing location is the Site:GroundTemperature:BuildingSurface object. This would be a great addition to the measure rather than being dependent on the user for the temperature calculations.

**Comment by mdahlhausen** [comment]
Moving this to the [openstudio-common-measures-gem repo](https://github.com/NREL/openstudio-common-measures-gem/issues/91).
