### ISSUE TITLE
Create DEER Prototype Building ALPHA Version has zero cooling load for all zones

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#458]
Input:
Education - Primary School: Split or Packaged DX Unit with Electric Heat
DEER 2017
CEC T24-CEC11

   ** Warning ** Calculated design cooling load for zone=EL1 EAST PERIM SPC (G.E1) ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design cooling load for zone=EL1 NNE PERIM SPC (G.NNE2) ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design cooling load for zone=EL1 SSE PERIM SPC (G.SSE3) ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design cooling load for zone=EL1 WEST PERIM SPC (G.W4) ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design cooling load for zone=EL2 EAST PERIM SPC (G.E3) ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design cooling load for zone=EL2 NORTH PERIM SPC (G.N2) ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design cooling load for zone=EL2 SSW PERIM SPC (G.SSW1) ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.

**Comment by mdahlhausen** [comment]
Fixed with [this commit](https://github.com/NREL/openstudio-standards/commit/d754365712142da794914164aebfc26f77f46f27).  The models were missing cooling design days.
