### ISSUE TITLE
Create DEER Prototype Building ALPHA Version creates a temporary classroom with an underground crawl space

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#459]
Inputs:
Education - Relocatable Classroom: Split or Packaged DX Unit with Heat Pump
DEER 2017
CEC T24-CEC11

I have never seen a temporary building with an underground crawlspace.

But if that is really the case, then the Outside Boundary Condition field of the walls of the crawlspace are listed incorrectly as Outside instead of Ground and this basement probably needs some extra objects to model the ground heat transfer that deep.

BuildingSurface:Detailed,
  EL1 East Wall (G.1.E6),                 !- Name
  Wall,                                   !- Surface Type
  DEER Insulated Wood Framed Exterior Wall R-16.95, !- Construction Name
  EL1 CrS (G.1) ZN,                       !- Zone Name
  Outdoors,                               !- Outside Boundary Condition
  ,                                       !- Outside Boundary Condition Object
  SunExposed,                             !- Sun Exposure
  WindExposed,                            !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  12.20724, -2.98991147848471e-015, 0,    !- X,Y,Z Vertex 1 {m}
  12.20724, -2.98991147848471e-015, -0.9144, !- X,Y,Z Vertex 2 {m}
  12.20724, 7.3152, -0.9144,              !- X,Y,Z Vertex 3 {m}
  12.20724, 7.3152, 0;                    !- X,Y,Z Vertex 4 {m}

![capture](https://user-images.githubusercontent.com/39242689/44939537-e2d33100-ad3a-11e8-8b67-29f0423ead0d.PNG)

   ** Warning ** CalcSurfaceCentroid: 4 Surfaces have the Z coordinate < 0.
   **   ~~~   ** ...in any calculations, Wind Speed will be 0.0 for these surfaces.
   **   ~~~   ** ...in any calculations, Outside temperatures will be the outside temperature + 9.750E-003 for these surfaces.
   **   ~~~   ** ...that is, these surfaces will have conditions as though at ground level.

**Comment by mdahlhausen** [comment]
Fixed with [this pull request](https://github.com/NREL/openstudio-standards/pull/463)
