### ISSUE TITLE
Create DEER Prototype Building ALPHA Version unable to calculate volume of E3 SW PERIM SPC (G.SW1) ZN

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#460]
Inputs:
Education - Secondary School: Split or Packaged DX Unit with Gas Furnace
DEER 2017
CEC T24-CEC11

It appears the space has no ceiling.

   ** Severe  ** For zone: E3 SW PERIM SPC (G.SW1) ZN it is not possible to calculate the volume from the surrounding surfaces so either provide the volume value or define all the surfaces to fully enclose the zone.
   ** Warning ** Indicated Zone Volume <= 0.0 for Zone=E3 SW PERIM SPC (G.SW1) ZN
   **   ~~~   ** The calculated Zone Volume was=0.00
   **   ~~~   ** The simulation will continue with the Zone Volume set to 10.0 m3. 
   **   ~~~   ** ...use Output:Diagnostics,DisplayExtraWarnings; to show more details on individual zones.

**Comment by mdahlhausen** [comment]
Fixed with [this pull request](https://github.com/NREL/openstudio-standards/pull/463)
