### ISSUE TITLE
Create DEER Prototype Building ALPHA Version has several unenclosed spaces

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#461]
Input:
Education - University: Packaged VAV System with Electric Heat
DEER 2017
CEC T24-CEC11

   ** Severe  ** For zone: E3 NORTH PERIM SPC (G.N2) ZN it is not possible to calculate the volume from the surrounding surfaces so either provide the volume value or define all the surfaces to fully enclose the zone.
   ** Warning ** Indicated Zone Volume <= 0.0 for Zone=E3 NORTH PERIM SPC (G.N2) ZN
   **   ~~~   ** The calculated Zone Volume was=0.00
   **   ~~~   ** The simulation will continue with the Zone Volume set to 10.0 m3. 
   **   ~~~   ** ...use Output:Diagnostics,DisplayExtraWarnings; to show more details on individual zones.
   ** Severe  ** For zone: E3 SOUTH PERIM SPC (G.S1) ZN it is not possible to calculate the volume from the surrounding surfaces so either provide the volume value or define all the surfaces to fully enclose the zone.
   ** Warning ** Indicated Zone Volume <= 0.0 for Zone=E3 SOUTH PERIM SPC (G.S1) ZN
   **   ~~~   ** The calculated Zone Volume was=0.00
   **   ~~~   ** The simulation will continue with the Zone Volume set to 10.0 m3. 
   **   ~~~   ** ...use Output:Diagnostics,DisplayExtraWarnings; to show more details on individual zones.
   ** Warning ** CalculateZoneVolume: 9 zones are not fully enclosed. For more details use:  Output:Diagnostics,DisplayExtrawarnings; 

![capture](https://user-images.githubusercontent.com/39242689/44940049-faacb400-ad3e-11e8-9cd5-528e9f5dbb10.PNG)

**Comment by asparke2** [comment]
Fixed in https://github.com/NREL/openstudio-standards/pull/463
