### ISSUE TITLE
Create DOE Prototype Building BCL measure does not have sufficient warmup days

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#464]
Input:
SecondarySchool
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

The warmup iterations is set to 25, which isn't enough to reach convergence. In particular the Max Heat Load Comparison = 0.2895 vs Loads Convergence Tolerance=4.00E-002

   ** Severe  ** CheckWarmupConvergence: Loads Initialization, Zone="CORNER_CLASS_2_POD_1_ZN_1_FLR_2 ZN" did not converge after 25 warmup days.
   **   ~~~   ** See Warmup Convergence Information in .eio file for details.
   **   ~~~   ** ...Environment(RunPeriod)="RUN PERIOD 1"
   **   ~~~   ** ..Max Temp Comparison = 1.94E-002 vs Temperature Convergence Tolerance=0.20 - Pass Convergence
   **   ~~~   ** ..Min Temp Comparison = 3.14E-002 vs Temperature Convergence Tolerance=0.20 - Pass Convergence
   **   ~~~   ** ..Max Heat Load Comparison = 0.2895 vs Loads Convergence Tolerance=4.00E-002 - Fail Convergence
   **   ~~~   ** ..Max Cool Load Comparison = 2.6355E-003 vs Loads Convergence Tolerance=4.00E-002 - Pass Convergence

**Comment by jiangithub** [comment]
25 days of warmup are normally sufficient. There might be other settings that are causing the convergence issue. The non-convergence level is not significant, assuming they are delta temperature and delta heat load from one iteration to another. So, we won't investigate too much time on this issue.
