### ISSUE TITLE
Create DOE Prototype Building BCL measure has HeatExchanger:AirToAir:SensibleAndLatent Average air volume flow rate is <50% or >130% warning approximately 59,000 times

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#465]
Input:
PrimarySchool
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

   *************  ** Warning ** HeatExchanger:AirToAir:SensibleAndLatent "PVAV_OTHER ERV":  Average air volume flow rate is <50% or >130% warning continues. Air flow rate ratio statistics follow.
   *************  **   ~~~   **   This error occurred 59081 total times;
   *************  **   ~~~   **   during Warmup 0 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=1.363695  Min=0.411155

**Comment by mdahlhausen** [comment]
This is typical of this object.
