### ISSUE TITLE
Create DOE Prototype Building BCL measure has Coil:Heating:DX:SingleSpeed Defrost Energy Input Ratio Function of Temperature Curve output at rated conditions = 0.787 which is supposed to be between 0.90 and 1.10

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#466]
Input:
SmallOffice
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

   ** Warning ** GetDXCoils: Coil:Heating:DX:SingleSpeed="CORE_ZN ZN PSZ-AC-1 HP HTG COIL 22 CLG KBTU/HR 7.7HSPF" curve values
   **   ~~~   ** ... Defrost Energy Input Ratio Function of Temperature Curve Name = CURVE BIQUADRATIC 13 output is not equal to 1.0 (+ or - 10%) at rated conditions.
   **   ~~~   ** ... Curve output at rated conditions = 0.787

**Comment by mdahlhausen** [comment]
This is captured in issue #550
