### ISSUE TITLE
Create DOE Prototype Building BCL measure has HeatExchanger:AirToAir:SensibleAndLatent Average air volume flow rate is <50% or >130% warning

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#467]
Input:
LargeOffice
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

If I'm reading this correctly, then the percantage is greater than 900% and occurs 1,778,108 times during the simulation.

** Warning ** HeatExchanger:AirToAir:SensibleAndLatent "VAV_MID WITH REHEAT ERV":  Average air volume flow rate is <50% or >130% warning continues. Air flow rate ratio statistics follow.
**   ~~~   **   This error occurred 1778108 total times;
**   ~~~   **   during Warmup 0 times;
**   ~~~   **   during Sizing 0 times.
**   ~~~   **   Max=9.298068  Min=9.079932

**Comment by lymereJ** [comment]
Moved to internal JIRA.
