### ISSUE TITLE
Create DOE Prototype Building BCL measure has HVAC errors in most zones

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#468]
Input:
SmallHotel
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

The following are specific to the MEETINGROOMFLR1 ZN zone, but similar problems with many other zones in the model, many greater than 1,000 times during the run period.

   ** Warning ** The Standard Ratings is calculated for Coil:Cooling:DX:SingleSpeed = MEETINGROOMFLR1 ZN SAC 1SPD DX AC CLG COIL 31KBTU/HR 13.0SEER but not at the AHRI test condition due to curve out of bound.
   **   ~~~   **  Review the Standard Ratings calculations in the Engineering Reference for this coil type. Also, use Output:Diagnostics, DisplayExtraWarnings for further guidance.

   ** Warning ** CalcDoe2DXCoil: Coil:Cooling:DX:SingleSpeed "MEETINGROOMFLR1 ZN SAC 1SPD DX AC CLG COIL 31KBTU/HR 13.0SEER" - Full load outlet air dry-bulb temperature < 2C. This indicates the possibility of coil frost/freeze. Outlet temperature = 0.79 C.
   **   ~~~   **  ...Occurrence info = RUN PERIOD 1, 01/01 18:15 - 18:18
   **   ~~~   ** ... Possible reasons for low outlet air dry-bulb temperatures are: This DX coil
   **   ~~~   **    1) may have a low inlet air dry-bulb temperature. Inlet air temperature = 17.272 C.
   **   ~~~   **    2) may have a low air flow rate per watt of cooling capacity. Check inputs.
   **   ~~~   **    3) is used as part of a HX assisted cooling coil which uses a high sensible effectiveness. Check inputs.

   *************  ** Warning ** CalcDoe2DXCoil: Coil:Cooling:DX:SingleSpeed="MEETINGROOMFLR1 ZN SAC 1SPD DX AC CLG COIL 31KBTU/HR 13.0SEER" - Full load outlet temperature indicates a possibility of frost/freeze error continues. Outlet air temperature statistics follow:
   *************  **   ~~~   **   This error occurred 181 total times;
   *************  **   ~~~   **   during Warmup 0 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=1.998716  Min=-1.645458

**Comment by mdahlhausen** [comment]
This is typical of these objects.
