### ISSUE TITLE
Create DOE Prototype Building BCL measure has a daylighting with 7.20E-002 of the zone controlled.

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#469]
Input:
LargeHotel
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

Fraction zone controlled by daylighting object is 7.20E-002, approximately zero.

** Warning ** GetDaylightingControls: Fraction of Zone controlled by the Daylighting reference points is < 1.0.
**   ~~~   ** ..discovered in "Daylighting:Controls" for Zone="LOBBY_FLR_1 ZN", only 7.20E-002 of the zone is controlled.

**Comment by lymereJ** [comment]
Will be addressed in #675
