### ISSUE TITLE
Create DOE Prototype Building BCL measure has severe error "Problem in interior solar distribution calculation (CHKBKS)"

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#470]
Input:
RetailStandalone
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

The only thing out of the ordinary I spotted was the roof was not convex.

   ** Severe  ** Problem in interior solar distribution calculation (CHKBKS)
   **   ~~~   **    Solar Distribution = FullInteriorExterior will not work in Zone=CORE_RETAIL ZN
   **   ~~~   **    because vertex 2 of back surface=CORE_RETAIL_WALL_EAST_1 is in front of receiving surface=CORE_RETAIL_ROOF
   **   ~~~   **    (Dot Product indicator=459.6689)
   **   ~~~   **    Check surface geometry; if OK, use Solar Distribution = FullExterior instead.

**Comment by mdahlhausen** [comment]
The solution is to split roof geometry to be convex.

**Comment by lymereJ** [comment]
Moved to internal JIRA.
