### ISSUE TITLE
Create DOE Prototype Building BCL measure has freezing occurring in water loops

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#471]
Input:
HighriseApartment
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

   *************  ** Warning ** GetSpecificHeatGlycol: Temperature out of range (too low) for fluid [WATER] specific heat **
   *************  **   ~~~   **   This error occurred 510790 total times;
   *************  **   ~~~   **   during Warmup 0 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=-2.713663E-004 {C}  Min=-2.028374 {C}

**Comment by lymereJ** [comment]
Issue identified. Tasked moved to our internal JIRA.
