### ISSUE TITLE
Create DOE Prototype Building BCL measure calculated design heating load is zero for 42 of 118 zones

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#474]
Input:
Outpatient
90.1-2010
ASHRAE 169-2006-2A
Not Applicable

Examples:
   ** Warning ** Calculated design heating load for zone=FLOOR 1 LOBBY HALL ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 1 LOCKER ROOM HALL ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 1 LOCKER ROOM ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 1 LOUNGE ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 1 NURSE HALL ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 1 NURSE JANITOR ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 1 NURSE STATION ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 1 NURSE TOILET ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 1 OFFICE ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 1 RECEPTION HALL ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 2 LOUNGE ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 2 NURSE STATION 1 ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 2 NURSE STATION 2 ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=FLOOR 2 RECEPTION HALL ZN is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.

**Comment by mdahlhausen** [comment]
This is expected for interior zones and is not an issue.
