### ISSUE TITLE
BCL measure TariffSelectionTimeAndDateDependentWithOffPeakDemandCharge fails with default parameters

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#477]
Running the measure gives

![measure fail](https://user-images.githubusercontent.com/39242689/45242086-9be9bc00-b2a3-11e8-9ff1-75cf8eda3ecf.PNG)

Complaining that "Argument peak_start_hour has no value." but it does have a value. From lines 80-85 in the measure.rb file

    # Adding argument for peak_start_hour
    peak_start_hour = OpenStudio::Ruleset::OSArgument.makeDoubleArgument("peak_start_hour", true)
    peak_start_hour.setDisplayName("Hour Peak Begins: Summer")
    peak_start_hour.setDescription("1-24")
    peak_start_hour.setDefaultValue(12)
    args << peak_start_hour

which is filled out by default in openstudio.

![var filled](https://user-images.githubusercontent.com/39242689/45242198-fb47cc00-b2a3-11e8-9115-6059ebde39ce.PNG)

The error occurs in line 143 of os_lib_helper_methods.rb

      arg_value = argument.valueDisplayName.to_f   # instead of valueAsDouble so it allows integer arguments as well

The argument variable is in a for each loop, with argument assigned "peak_start_hour" in the first iteration of the loop.

**Comment by mldichter** [comment]
I was able to easily fix the measure by commenting out the code related to OsLib_HelperMethods.checkDoubleAndIntegerArguments(), which only checks that the user input for hour, day, and month are between 0,24 and 1,31 and 1,12 respectively.

![fix](https://user-images.githubusercontent.com/39242689/45242950-e6b90300-b2a6-11e8-9ca9-034d703e1982.PNG)

I don't know what's wrong with the OsLib_HelperMethods code, but argument validation would be unnecessary with choice arguments instead of a text field and code to ensure user input is valid for these variables.

**Comment by mdahlhausen** [comment]
@DavidGoldwasser this is a NREL BCL measure issue.  Can you invite @mldichter to the Openstudio-measures repository and move this issue there?

**Comment by DavidGoldwasser** [comment]
@mldichter should get an invite soon, IT can take a day or to sometimes.

**Comment by mldichter** [comment]
I joined but the measure isn't there. Looks like the measure wasn't made by NREL, it was made by Integral Group Modeling.

**Comment by mdahlhausen** [comment]
NREL does not maintain this measure.
