### ISSUE TITLE
BCL measure TariffSelectionTimeAndDateDependentWithMaximumDemandCharge fails with default parameters

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#478]
Same issue and fix as [BCL measure TariffSelectionTimeAndDateDependentWithOffPeakDemandCharge fails with default parameters](https://github.com/NREL/openstudio-standards/issues/477) Maximum vs OffPeak in the measure name.

**Comment by mdahlhausen** [comment]
NREL does not maintain this measure.
