### ISSUE TITLE
PRM: implement SAT reset for Sys 5 to 8

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#48]
G3.1.3.12 Supply Air Temperature Reset (Systems 5 through 8).
The air temperature for cooling shall be reset higher by 5°F under the minimum cooling load conditions.

**Comment by MatthewSteen** [comment]
We use the SetpointManagerWarmest for these AirLoopHVACs.

**Comment by jmarrec** [comment]
So do I.

I just noticed that there are actually methods already planned for this, probably by @asparke2. See https://github.com/NREL/openstudio-standards/blob/baseline_automation/openstudio-standards/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb#L1940

Couple of things:
- they use a SPM OA Reset. I think warmest is better
- My test model ends up without it because it's only implemented for 2010 and 2013
- The `is_supply_air_temperature_reset_required` says no for CZ 1A, 2A and 3A [here](https://github.com/NREL/openstudio-standards/blob/baseline_automation/openstudio-standards/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb#L1905). I think this is just a code compliance exemption, per App G I think you still ought to use a SAT reset.
- It's called way too late in the measure triggered on [this line](https://github.com/NREL/openstudio-standards/blob/baseline_automation/openstudio-standards/lib/openstudio-standards/standards/Standards.Model.rb#L217). It should be done before doing the first sizing run with HVAC

**Comment by asparke2** [comment]
Fixed on Master:
https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.Model.rb#L174
calls
https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb#L146
calls
https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb#L2299
