### ISSUE TITLE
Missing objects and parameters in the geometry osm files

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#486]
At stripmall and primary school (likely other prototypes), some objects and parameters in the osm model are not given, such as the simulation control, runperiod, shadowcalculation, loads convergence tolerance value, temperature convergence tolerance value, min and max number of warmup days, etc.  Proper objects need to be inserted and parameters need to be corrected in the osm files in the   "data\geometry" folder for ASHRAE 90.1 and ASHRAE90.1-2013 in particular.
--

**Comment by mdahlhausen** [comment]
These objects are defaulted when the .osm is written.  Why do they need to be included in the data\geometry .osm files?
If a model requires specialized convergence tolerances to avoid an error, there is likely some bigger issue with sizing, geometry, or constructions.
