### ISSUE TITLE
PRM: Setting pump rated power isn't implemented correctly

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#49]
https://github.com/NREL/openstudio-standards/blob/baseline_automation/openstudio-standards/lib/openstudio-standards/standards/Standards.Pump.rb#L36

Eplus actually assumes an impeller efficiency of 0.78 to determine the total efficiency
See the engineer reference guide for [Pump Sizing](http://bigladdersoftware.com/epx/docs/8-4/engineering-reference/component-sizing.html#pump-sizing)

    Rated_Power_Use = Rated_Volume_Flow_Rate * Rated_Pump_Head / Total_Efficiency
    Rated_Power_Use / Rated_Volume_Flow_Rate =  Rated_Pump_Head / Total_Efficiency
    Total_Efficiency = Motor_Efficiency * Impeler_Efficiency

**Comment by asparke2** [comment]
In the PNNL document (pdf 251), they specify assumptions for impeller and motor efficiencies for determining the baseline power.  However, their assumptions don't like up with the E+ default of 0.78 for impeller efficiency for sizing purposes.  I think your approach makes sense given the E+ constraint.

**Comment by asparke2** [comment]
Pulled suggestions into baseline_automation
