### ISSUE TITLE
Order of HVAC system components

### ISSUE THREAD

**Issue by YulongXieGitHub** [NREL/openstudio-standards#491]
The order of the HVAC system components is different between the OS and the legacy models at primary school and stripmall retail (likely other prototypes).  Sensitivity analysis indicates that the order of the components has impacts on the energy results.
--

**Comment by mdahlhausen** [comment]
Can you specify which components and which systems?

Some of component orders were intentionally changed to properly size systems, especially for systems with both air-based and zonal systems.
