### ISSUE TITLE
design days missing from ddy file

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#499]
At the url
https://energyplus.net/weather-location/north_and_central_america_wmo_region_4/USA/CA-Zones/CZ14RV2
for CA climate zone 14

![no design days](https://user-images.githubusercontent.com/39242689/45981834-3cadda80-c00b-11e8-8bb5-1de26ab8d1e7.PNG)

the ddy file downloaded does not have any design day objects in it.

![ep no design days](https://user-images.githubusercontent.com/39242689/45981848-4cc5ba00-c00b-11e8-922e-fcc259c460be.PNG)

**Comment by mdahlhausen** [comment]
This isn't an openstudio-standards issue.  Contact whoever maintains the EnergyPlus weather website.

If you need .ddy files for California Climate Zone 14, the [CEC default city](http://www.energy.ca.gov/maps/renewable/building_climate_zones.html) for CZ 14 is Palmdale, CA.  [.ddy file available here](https://github.com/NREL/openstudio-standards/blob/master/data/weather/PALMDALE_723820_CZ2010.ddy).
