### ISSUE TITLE
Create DOE Prototype Building BCL measure has carpet in most rooms, kitchens, bathrooms, gyms, etc

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#500]
Input:
SecondarySchool
90.1-2013
ASHRAE 169-2006-2A
Not Applicable

BuildingSurface:Detailed,
  Gym_ZN_1_FLR_1_Floor,                   !- Name
  Floor,                                  !- Surface Type
  Typical Insulated **_Carpeted_** 8in Slab Floor, !- Construction Name
  Gym_ZN_1_FLR_1 ZN,                      !- Zone Name
  Ground,                                 !- Outside Boundary Condition
  ,                                       !- Outside Boundary Condition Object
  NoSun,                                  !- Sun Exposure
  NoWind,                                 !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  38, 52, 0,                              !- X,Y,Z Vertex 1 {m}
  38, 0, 0,                               !- X,Y,Z Vertex 2 {m}
  0, 0, 0,                                !- X,Y,Z Vertex 3 {m}
  0, 52, 0;                               !- X,Y,Z Vertex 4 {m}

BuildingSurface:Detailed,
  Kitchen_ZN_1_FLR_1_Floor,               !- Name
  Floor,                                  !- Surface Type
  Typical Insulated **_Carpeted_** 8in Slab Floor, !- Construction Name
  Kitchen_ZN_1_FLR_1 ZN,                  !- Zone Name
  Ground,                                 !- Outside Boundary Condition
  ,                                       !- Outside Boundary Condition Object
  NoSun,                                  !- Sun Exposure
  NoWind,                                 !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  24, 9, 0,                               !- X,Y,Z Vertex 1 {m}
  24, 0, 0,                               !- X,Y,Z Vertex 2 {m}
  0, 0, 0,                                !- X,Y,Z Vertex 3 {m}
  0, 9, 0;                                !- X,Y,Z Vertex 4 {m}

BuildingSurface:Detailed,
  Bathrooms_ZN_1_FLR_1_Floor,             !- Name
  Floor,                                  !- Surface Type
  Typical Insulated **_Carpeted_** 8in Slab Floor, !- Construction Name
  Bathrooms_ZN_1_FLR_1 ZN,                !- Zone Name
  Ground,                                 !- Outside Boundary Condition
  ,                                       !- Outside Boundary Condition Object
  NoSun,                                  !- Sun Exposure
  NoWind,                                 !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  15, 14, 0,                              !- X,Y,Z Vertex 1 {m}
  15, 0, 0,                               !- X,Y,Z Vertex 2 {m}
  0, 0, 0,                                !- X,Y,Z Vertex 3 {m}
  0, 14, 0;                               !- X,Y,Z Vertex 4 {m}

**Comment by mdahlhausen** [comment]
Good catch.  We'll revise the defaults for floors in those spaces.

**Comment by mdahlhausen** [comment]
@asparke2 how should we distinguish between spaces that have carpet and those that don't?

**Comment by leijerry888** [comment]
All "Carpeted" floor constructions are confirmed to be for ground floors. Our team member Juan is working on using F/C factor method to model ground floors, meaning in a future update, all these floors will be replaced. Thus, this issue is closed.
