### ISSUE TITLE
Create DOE Prototype Building BCL measure has ceilings with exposed insulation and no drywall

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#503]
Input:
LargeHotel
90.1-2013
ASHRAE 169-2006-2A
Not Applicable

The exposed building material in the ceilings is raw insulation, the drywall is missing from the construction.

Construction,
    LargeHotel Interior Ceiling,  !- Name
    CP02 CARPET PAD,         !- Outside Layer
    100mm Normalweight concrete floor,  !- Layer 2
    Nonres_Floor_Insulation; !- Layer 3

**Comment by mdahlhausen** [comment]
Fixed with #748
