### ISSUE TITLE
HVAC Sizing: get results from TabularDataWithStrings?

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#51]
It seems that ComponentSizes is currently not being maintained. See [here](https://unmethours.com/question/15081/sql-file-why-are-some-parameters-not-present-in-componentsizes/)

**Comment by asparke2** [comment]
Will keep using ComponentSizes until I hit an issue.  Seems to be working well now.

**Comment by jmarrec** [comment]
I added the method to get it from `TabularDataWithStrings`, not sure if you merged that in
