### ISSUE TITLE
PRM: Fix Chilled Water Loop pumping configuration

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#52]
With a 100 tons chiller I ended up with a Constant primary variable secondary pumping instead of having a constant primary constant secondary (riding the pump curve)

**Comment by jmarrec** [comment]
After thinking about it, I think what you actually need:

- One primary, constant-speed, branch pump per chiller on the ChW Loop (supply side)
- One Secondary pump (VSD or constant speed depending if > 300 ton or not) on the demand side
- On the condenser loop, one constant-speed branch pump for each chiller (on the demand side)

## References:

### Chilled Water Loop Side:

> PNNL Paper, section 3.7.5 Pumps

> ASHRAE 90.1-2007 - Section 6.5.4.2 - Pump Isolation
> When a chilled-water plant includes more than one chiller, provisions shall be made so that
the flow in the chiller plant can be automatically reduced, correspondingly, when a chiller is shut down.

> ASHRAE 90.1-2010 User's Manual,  section HVAC Systems | Prescriptive Path 6.5 (page '6-101' or 232/470)

![2016-02-22 14_57_34-90 1-2010 user s manual](https://cloud.githubusercontent.com/assets/5479063/13220158/d64296c0-d974-11e5-8458-5f7fa16d3605.png)


### Both

> ASHRAE 90.1-2007, Appendix G, section **G3.1.3.11:**
> Each chiller shall be modeled with separate condenser water and chilled-water pumps interlocked to operate with the associated chiller.


> ASHRAE 90.1-2010, Appendix G, **G3.1.3.11 Heat Rejection (Systems 7 and 8).**
> Each chiller shall be modeled with separate condenser water and chilled water pumps interlocked to operate with the associated chiller.

**Comment by eringold** [comment]
> On the condenser loop, one constant-speed branch pump for each chiller (on the demand side)

Is this even possible? It seems like it would violate the [pump rule](http://bigladdersoftware.com/epx/docs/8-4/engineering-reference/pumps.html#summary-of-pump-rules): 
> A Pump, if present, in the demand side of plant loop must be the first component of the inlet branch.

This seems to mean only one pump is allowed on the demand side, before the splitter.

**Comment by jmarrec** [comment]
Then maybe you have one condenser loop per chiller?

**Comment by jmarrec** [comment]
The PRM for chiller loop still has bugs: one of my two chillers (> 300 tons) ends up not connected to the condenser loop.

The SPM is constant temperature instead of being an outdoor air reset

**Comment by jmarrec** [comment]
Also the condenser water loop ends up with a CT Variable speed for 90.1-2007 while G3.1.3.11 says axial fan cooling tower with two-speed fans.

**Comment by lincolnharmer** [comment]
I just finished adding some new methods to the model class that may address these issues. I'll commit the changes soon after I test them some more today

**Comment by asparke2** [comment]
@jmarrec @eringold @lincolnharmer Just made a commit to the baseline_automation_90.1_fixes branch that I believe addresses the issues you've listed.

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/commit/0eaf0d5fb82d57097bb8f0270fa7425af13318df
