### ISSUE TITLE
Possible fixes for some of the DOE reference models warnings and errors

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#522]
An organization called the Regional Technical Forum had modified the DOE 2014 reference models and got rid of many of the severe errors and warnings. The link is to the models is here:
https://nwcouncil.app.box.com/v/SimModelsHVACInteractionZIP
The only downside is these are not for California.

However, the same organization recently had a request for proposals to bring the DOE reference models up to date, which they might post on their website. The link to the proposal is here:
https://rtf.nwcouncil.org/request-proposals-commercial-building-model-enhancements-2018
Once again, the models are not specific to California, but some of the equipment might be compatible with California building standards. These could be used to fix at least some of the numerous errors present in the idf files created by the Create DOE Prototype Building BCL measure.

**Comment by mldichter** [comment]
Request that this issue be moved to NREL/OpenStudio-measures issues.

**Comment by jiangithub** [comment]
@mdahlhausen This set of RTF models are either based on the EnergyPlus Prototypes or the EnergyPlus Reference Models but not the OpenStudio Standards. The linked models are preliminary and the work is still in progress. The RTF and its contractor use these models to represent the existing building stock in the Northwest and are supposed to be very different from the EnergyPlus and OpenStudio prototypes. It is not practical to review the current draft RTF models to identiy fixes to the  Create DOE Prototype Building BCL measure.

**Comment by mdahlhausen** [comment]
Understood. Closing this issue per Jiang's comments above.
