### ISSUE TITLE
Openstudio refuses to add a Fan:SystemModel object's name to a Branch object

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#523]
This problem is present in Openstudio 2.7.0 and Energyplus 9.0. Some troubleshooting is detailed here:
https://unmethours.com/question/34887/how-to-change-idd-file-to-allow-fansystemmodel-on-branch/?comment=34978#post-id-34978
Changing the idd files fixes the orange highlighted fields in the IDF Editor, but changing the energyplus nor openstudio idd files changed Openstudio's refusal to write a Fan:SystemModel object's name to a Branch object.

I was told that the fix would require compiling Openstudio, which looked beyond my capabilities. Is there an estimate of when a fix will be included and released for download and installation?

**Comment by mdahlhausen** [comment]
This is an OpenStudio issue, not an openstudio-standards issue.
