### ISSUE TITLE
Openstudio 2.7.0 runs measure which simultaneously outputs "Result: Success" and "Failed."

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#524]
Here is a link to a google drive zip for the files of a very small working example: https://drive.google.com/file/d/1T9w_Zgu9-a5Drjro4zAkSjiaFjZw_Vu-/view?usp=sharing

![success and failure](https://user-images.githubusercontent.com/39242689/47520668-a1946480-d845-11e8-91ec-7cdd9df14658.PNG)

**Comment by mdahlhausen** [comment]
This is an OpenStudio issue, not an openstudio-standards issue.
