### ISSUE TITLE
PRM: Potential bug in Standards.Space.addDaylightingControls

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#53]
https://github.com/NREL/openstudio-standards/blob/baseline_automation/openstudio-standards/lib/openstudio-standards/standards/Standards.Space.rb#L1389

https://github.com/NREL/openstudio-standards/blob/baseline_automation/openstudio-standards/lib/openstudio-standards/standards/Standards.Space.rb#L1392

I think both of these lines should read `req_top_ctrl = false` no?

**Comment by jmarrec** [comment]
In same function, 
https://github.com/NREL/openstudio-standards/blob/baseline_automation/openstudio-standards/lib/openstudio-standards/standards/Standards.Space.rb#L1875

The comment is "Sensor 2 controls secondary area", but the computation is actually "Sensor 2 controls half of the secondary area". I don't have a copy of ASHRAE 2013, so not sure which it is.

**Comment by jmarrec** [comment]
There a few more problems with the current implementation, especially relative to the placement of the sensor:

- The sensor is based relatively to the south facade by priority (I think)
- There is no "reality check" when offset the sensor from the window [here](https://github.com/NREL/openstudio-standards/blob/baseline_automation/openstudio-standards/lib/openstudio-standards/standards/Standards.Space.rb#L1937). Currently this could lead to a sensor placed outside of the space. For example case where you have a narrow corridor (eg: 8ft) and a high head_height (10 ft)

Looking at daylighted_areas method:

- Around [here](https://github.com/NREL/openstudio-standards/blob/baseline_automation/openstudio-standards/lib/openstudio-standards/standards/Standards.Space.rb#L833) you supposedly end up with a single joined polygon for the different daylighting areas and the floor polygon. Why not just using OpenStudio.intersect?

```ruby
if combined_toplit_polygons.size == 1 && floor_polygons.size == 1
      intersection = OpenStudio.intersect(combined_toplit_polygons[0], combined_floor_polygons[0], 0.01)
      if intersection.empty?
        OpenStudio::logFree(OpenStudio::Warn, "openstudio.model.Space", "***Intersection failed for combined_pri_sidelit_polygons***")
      else
        intersection = intersection.get
        combined_toplit_polygons = [intersection.polygon1]
      end
    else
      OpenStudio::logFree(OpenStudio::Warn, "openstudio.model.Space", "***Space #{self.name} - combined_toplit_polygons (#{combined_toplit_polygons.size}) or combined_floor_polygons (#{combined_floor_polygons.size}) size isn't 1***")
    end
```

- The primary and secondary sensors end up being placed exactly at the same location

- I'd suggest maybe we can actually return the centroid of the intersected polygons (see above) and place the sensor there? Any problems with this I didn't see?

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/pull/106
