### ISSUE TITLE
BCL measure AedgK12SlabAndBasement FAILS

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#534]
Here is a screenshot. Just download the measure about 15 minutes ago.

![bcl_measure_error](https://user-images.githubusercontent.com/39242689/48233017-7ee76d00-e368-11e8-96d2-942aba8d9194.PNG)

There is a similarly named function in os_lib_helper_methods.rb in the resources directory of the measure.

def self.checkDoubleAndIntegerArguments(runner, user_arguments, arg_check_hash)

**Comment by DavidGoldwasser** [comment]
@mldichter This measure should only be able to be downloaded from BCL through OS App or PAT with OpenStudio 1.x versions. The max version supported is 1.14.0
https://bcl.nrel.gov/node/82249

Can you describe to me if you recently downloaded this with 2.7.0, if you had it in your local BCL and were able to add it to OS app or PAT project, or if this is an older OS App or PAT project that has been upgrade to 2.7.0. Based on this can file an issue in another repository and close this one.

OpenStudio doesn't use the EnergyPlus slab and basement pre-processer anymore, so there is not a way for this measure to work in the current version of OpenStudio. There is Zero Energy Design guide measure that uses newer EnergyPlus Ground Domain objects, but I'm not very happy with this.
[ZEDG K12 Insert Ground Domain E+ Kusdua](https://bcl.nrel.gov/node/84754)

At some point in the future we may implement ground modeling with Kiva.

**Comment by mldichter** [comment]
@DavidGoldwasser Sorry. I don't remember. I think I downloaded a local copy of the measure near the time I submitted this issue, 8 Nov 2018, and then went through the code to try and figure out what was going on.

It sounds like this measure is either outdated or not supported in openstudio, but is on the ToDo list for more features to be added. I'll go ahead and close the issue.
