### ISSUE TITLE
Improve elevator logic

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#558]
Improve the default elevator power and schedule assumptions for non-doe prototype elevators.

[Related to this issue in la100 project](https://github.com/NREL/la100-comstock/issues/48).

Tasks:
- Decide whether to apply elevators before or after HVAC sizing
  - if before, adjust logic to add elevators at the same time as other internal loads
- Check design power and schedule values, make sure total annual energy use aligns with benchmark models
  - Background sources:
    - http://www.ibpsa.org/proceedings/BS2011/P_1815.pdf
    - https://www.thyssenkruppelevator.com/Tools/energy-calculator
    - https://aceee.org/files/pdf/white-paper/elevators2005.pdf
    - http://kms.energyefficiencycentre.org/sites/default/files/a1501.pdf
    - *** https://www.researchgate.net/publication/275951580_Elevator_Energy_Simulation_Model
    - https://www.nrel.gov/docs/fy15osti/63807.pdf
- Research elevator use profiles 
  - https://www.sciencedirect.com/science/article/pii/S235271021630136X
  - *** https://www.researchgate.net/publication/275951580_Elevator_Energy_Simulation_Model
  - options:
    - modify occupancy schedule by some factor (e.g., entire building occupancy schedule divided by 2, or some other algorithm to generate the schedule based on number of floors, etc.
    - create new schedule from report data, set this in the schedule field in the openstudio-standards spreadsheet
  - allow for both?  e.g., generate schedule if none is defined
(optional if time)
- Create tests for DEER prototype elevators, similar to DOE prototypes
- Adjust methods to account for different elevator technologies, e.g. regenerative braking, geared, gearless, vs. hydraulic elevators, cab lighting and fan types, etc.

**Comment by mdahlhausen** [comment]
@mpraprost is this complete?  can we close this issue?

**Comment by mpraprost** [comment]
@mdahlhausen yes, elevators changes were committed march 22 to the feature/elevators branch. just needs to be merged, I think
