### ISSUE TITLE
Create DOE Prototype Building BCL measure adds duplicate InternalMass objects

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#560]
The idf created for the Full Service Restaurant has InternalMass objects duplicated for the zones. The previous version of this idf before being updated to Title 24 in the BCL measure has only Dining Mass and Kitchen Mass objects with the same fields as here. This probably occurred because the code added a Dining Mass and Kitchen Mass object multiple times, in which case openstudio appends a number to the end of the object name.

Running the idf with and without the duplicate InternalMass objects removed used different amounts of energy. The duplicate objects should be removed from the outputted idf file for correct behavior.

InternalMass,
    Dining Mass,             !- Name
    InteriorFurnishings,     !- Construction Name
    Dining ZN,               !- Zone Name
    743.49614298;            !- Surface Area {m2}

InternalMass,
    Dining Mass 1,           !- Name
    InteriorFurnishings,     !- Construction Name
    Dining ZN,               !- Zone Name
    743.49614298;            !- Surface Area {m2}

InternalMass,
    Kitchen Mass,            !- Name
    InteriorFurnishings,     !- Construction Name
    Kitchen ZN,              !- Zone Name
    278.8104884;             !- Surface Area {m2}

InternalMass,
    Kitchen Mass 1,          !- Name
    InteriorFurnishings,     !- Construction Name
    Kitchen ZN,              !- Zone Name
    278.8104884;             !- Surface Area {m2}

InternalMass,
    Kitchen Mass 2,          !- Name
    InteriorFurnishings,     !- Construction Name
    Kitchen ZN,              !- Zone Name
    278.8104884;             !- Surface Area {m2}

InternalMass,
    Kitchen Mass 3,          !- Name
    InteriorFurnishings,     !- Construction Name
    Kitchen ZN,              !- Zone Name
    278.8104884;             !- Surface Area {m2}

**Comment by mldichter** [comment]
Error also present in the Warehouse model, which makes a big difference in the simulation from the amount of mass stored there.

!-   ===========  ALL OBJECTS IN CLASS: INTERNALMASS ===========

InternalMass,
    Zone1 Office Mass,       !- Name
    InteriorFurnishings,     !- Construction Name
    Zone1 Office ZN,         !- Zone Name
    473.759293161193;        !- Surface Area {m2}

InternalMass,
    Zone2 Fine Storage Mass, !- Name
    InteriorFurnishings,     !- Construction Name
    Zone2 Fine Storage ZN,   !- Zone Name
    2786.81937153644;        !- Surface Area {m2}

InternalMass,
    Zone3 Bulk Storage Mass, !- Name
    InteriorFurnishings,     !- Construction Name
    Zone3 Bulk Storage ZN,   !- Zone Name
    6409.68455453379;        !- Surface Area {m2}

InternalMass,
    Zone3 Bulk Storage Mass 1,  !- Name
    InteriorFurnishings,     !- Construction Name
    Zone3 Bulk Storage ZN,   !- Zone Name
    6409.68455453379;        !- Surface Area {m2}

InternalMass,
    Zone3 Bulk Storage Mass 2,  !- Name
    InteriorFurnishings,     !- Construction Name
    Zone3 Bulk Storage ZN,   !- Zone Name
    6409.68455453379;        !- Surface Area {m2}

**Comment by mdahlhausen** [comment]
Fixed with pull #591
