### ISSUE TITLE
apply_performance_rating_method_baseline_window_to_wall_ratio

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#57]
> WWR reduction will be done by raising sill height.  This causes the least impact on the daylighting area calculations and controls placement.

It'll work well for perfectly rectangular windows, but it fails in my case, notably because I have a window with 4 sides that's not perfect, and due to rounding error the method will end up creating a 4-sided windows that REALLY isn't rectangular.

In my opinion we should resize all windows around the centroid, which means it'll work nicely for all 3-sided (it's called a triangle I'm told) and 4-sided windows (@asparke2 I had already mentioned this in a @Todo)

What do you think? If you agree, I already have the code to do that.

**Comment by jmarrec** [comment]
https://unmethours.com/question/10932/reducing-wwr-to-40-which-approach/


---- 

Also, this is more a question about proper interpretation of 90.1, but should you include the adiabatic area into the wwr calculation?

https://unmethours.com/question/4709/wall-boundary-condition-when-abutting-an-adjacent-building/

As far as I can tell, the language just says "gross above-grade wall area"...

**Comment by asparke2** [comment]
@jmarrec Yeah let's put in your code.  You want to make a branch and PR, or send me the code?  Either is fine by me.

**Comment by jmarrec** [comment]
I can do the change tomorrow hopefully, or you I can paste the code now if you want.

**Comment by asparke2** [comment]
If you haven't worked on it yet, just email me the code and I can fold it in.

**Comment by jmarrec** [comment]
I'm sorry, I've been traveling to the US...

I uploaded my measure here: https://github.com/jmarrec/OpenStudioMeasures/blob/master/Resize%20Existing%20Windows%20To%20Match%20A%20Given%20WWR/measure.rb

**Comment by asparke2** [comment]
Very elegant!  I've just added it to Model.SubSurface as a method called `reduce_area_by_percent_by_shrinking_toward_centroid(percent_reduction)` and I'm testing it out on some user-created models now.

**Comment by jmarrec** [comment]
It's only a few lines but I had to refresh my vectors/trigonometry for it :)

Let me know how the testing goes, I've tried it on a model with complex/bad geometry and it seemed to work fine but that's not what I call extensive testing

Envoyé de mon iPhone

**Comment by macumber** [comment]
Not sure if these would help but OpenStudio has [getCentroid](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/utilities/geometry/Geometry.hpp#L51) and [moveVerticesTowardsPoint](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/utilities/geometry/Geometry.hpp#L90) methods.

**Comment by jmarrec** [comment]
Looks exactly like what I'm doing, but  probably won't result in less lines of code

Envoyé de mon iPhone

**Comment by jmarrec** [comment]
@asparke2: how did the testing go? (just checking if we can close it or not)

**Comment by asparke2** [comment]
It works like a charm.  It is currently in the baseline_automation_90.1_fixes branch, so I'll close the issue once it gets merged into Master.

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/commit/0eaf0d5fb82d57097bb8f0270fa7425af13318df
