### ISSUE TITLE
Create DOE Prototype Building BCL measure has water heater providing hot water to WaterUse:Equipment object with target temperature below freezing

### ISSUE THREAD

**Issue by mldichter** [NREL/openstudio-standards#571]
The FullServiceRestaurant model has a WaterUse:Equipment object with a target temperature of 15.5F = -9.1C, a.k.a. ice. This is probably modeling water that is straight from the water main, but the WaterUse:Equipment is on the demand side of a plantloop with a 6.0 gal WaterHeater:Mixed object, which is also providing hot water to another plantloop through a heat exchanger.

Request that the Service Water Loop and Main Service Water Loop be remade to reflect that one of the WaterUse:Equipment objects requires no hot water.

**Comment by mldichter** [comment]
Request that this issue be moved to NREL/OpenStudio-measures issues.

**Comment by lymereJ** [comment]
@mldichter, do you know for which template and location this used to happened? I checked a few cases and couldn't reproduced what you reported.

**Comment by mldichter** [comment]
@lymereJ Sorry, but that was over a year ago. The models have undergone several revisions since then. It may not be an issue any more.
