### ISSUE TITLE
space_apply_infiltration_rate(space) results in no infiltration for DOE Ref Pre-1980 and DOE Ref 1980-2004 

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#575]
They don't have a template specific logic rend relies on the default that uses 0
https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.Space.rb#L1294-L1297

I think we should add template specific code for these vintages based on what was used for the reference buildings. I'm also not a big fan of the default of 0, I'd almost rather have it fail then not add infiltration. This doesn't affect the DOE prototype measures, but it does impact create_typical_building_from_model.

cc: @macumber @rHorsey @mdahlhausen @asparke2 

I'm assigning myself, but if someone beats me to it that is fine, but would be nice to get in 2.8.0

**Comment by DavidGoldwasser** [comment]
Information about ref buildings from section 5.3.2 Infiltration 
in U.S. Department of Energy Commercial Reference Building Models of the National Building Stock PDF
https://www.nrel.gov/docs/fy11osti/46861.pdf

> For existing buildings, we turn to measured airtightness data. Persily (1998) collected data from
139 buildings that showed a wide scatter in airtightness and little correlation between building
age and airtightness. The average leakage rate across all building types and locations was 1.5
cfm/ft2 at 0.3 in. w.c. (7.5 L/s/m2 at 75 Pa) of above-grade envelope area. This number is used for the pre-1980 and post-1980 reference building models.

**Comment by mdahlhausen** [comment]
[Initial commit to fix this](https://github.com/NREL/openstudio-standards/tree/fix/doe_ref_infiltration_default).  We may need additional logic to override the defaults when making the DOE ref prototypes to use 1.5 instead of 1.8 cfm/ft2 exterior surface area at 75 Pa.

**Comment by mdahlhausen** [comment]
Fixed with pull #576
