### ISSUE TITLE
Standards 'intended surface type' and 'standards construction type' don't line up with available options in OpenStudio

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#60]
OpenStudio sets 'Standards Construction Types' based on 'Intended Surface Type' inputs [here](https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/model/StandardsInformationConstruction.cpp#L84). The openstudio_standards measure looks up baseline construction properties based on these inputs. However, the available options in OpenStudio do not cover all of the cases defined in the standards data. For example, OpenStudio has no Standards Construction Type options for Intended Surface Type = ExteriorWindow, but the standards spreadsheet defines window constructions based on Standards Construction Types = "Metal Framing (all other)", "Nonmetal Framing (all)", etc. There are multiple other discrepancies for different surface types. 

If the OpenStudio measure tags are to be used for the standards information lookup, the available options should match the lookup values in the standards data.

**Comment by eringold** [comment]
One potential fix might be to parse the standards json for intended surface types (i.e. [this](https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/model/StandardsInformationConstruction.cpp#L82) todo) in StandardsInformationConstruction.cpp, perhaps the same way that it's done in StandardsInformationMaterial.cpp: https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/model/StandardsInformationMaterial.cpp#L66

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/commit/0eaf0d5fb82d57097bb8f0270fa7425af13318df
