### ISSUE TITLE
Large Hotel Lobby uses wrong occupancy schedule

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#600]
Moved from https://github.com/NREL/OpenStudio/issues/1020

From @DavidGoldwasser:

> It is using the general hotel occupancy schedule, it should be using the lobby specific occupancy schedule. I need to update the spreadsheet to reflect this and then re-generate the schedules. Spot checking other areas this is fine, may have just been isolated error on the spreadsheet. This wasn't evident prior to 1.3.0 because it didn't impact the old templates, only people using on demand generator.

From the spreadsheet:

![image](https://user-images.githubusercontent.com/5479063/53485177-d891b580-3a85-11e9-8090-4f49b97e7173.png)

There is a `HotelLarge Lobby_Occ_Sch` (same applies to Laundry, etc)

**Comment by mdahlhausen** [comment]
There are some other space type issues in pull #586 that need fixing, so we will include the hotel lobby occ schedule with that.

**Comment by mdahlhausen** [comment]
I've changed the schedules in the spreadsheet and will commit them to master with #586  once those changes are done.

**Comment by jiangithub** [comment]
This is not a single issue in the prototypes. We need to review all schedules and explore opportunities to establish schedules for occupancy sensor savings and maybe make them space type specific. Let's close this issue and find an opportunity to review all together.
