### ISSUE TITLE
Error on log message when adding daylighting to space that isn't assigned to zone

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#604]
https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.Space.rb#L1017

```NameError: undefined local variable or method `name' for #<ASHRAE9012013:0x007f9f93f2bef0>```

If you search the file for `{name.` there are a few more instances that may also need to be updated.

**Comment by mdahlhausen** [comment]
Fixed [this commit](https://github.com/NREL/openstudio-standards/commit/14978f2e8ae3db7522ecfe2b53aa6c8d97b03e16)

**Comment by DavidGoldwasser** [comment]
@mdahlhausen did you see `.name` is used in few other places in this file for log files without `space` front of it. If you have not looked at them, might be worth checking it out.

**Comment by mdahlhausen** [comment]
I did look.  `name` is passed as as an argument in the other methods, so no error expected.
