### ISSUE TITLE
ground contacted surfaces are being assigned empty constructions

### ISSUE THREAD

**Issue by lincolnharmer** [NREL/openstudio-standards#62]
this causes the sizing simulations to fail

**Comment by eringold** [comment]
Related to https://github.com/NREL/openstudio-standards/issues/60

Available options of 'Standards Construction Type' for 'Intended Surface Type' = GroundContanctFloor in OpenStudio are shown [here](https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/model/StandardsInformationConstruction.cpp#L142). The openstudio_standards spreadsheet (or json), is expecting values of "Mass", "Metal Building", and "Steel Building".
