### ISSUE TITLE
PRM: Add Standard 90.1-2007 'Laboratory' space type

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#63]
No 'Laboratory' space type exists for Standard 90.1-2007 in OpenStudio_Standards_space_types.json.  I think, at least as far as loads are concerned, the 2007 Lab space is essentially the same as the 2004 Lab space.

**Comment by mdahlhausen** [comment]
Laboratory space types now exist for Hospital and Laboratory building types in 90.1-2004 and 90.1-2007.
