### ISSUE TITLE
Support ASHRAE 90.1-2013 Table 3.1.1-3 Baseline system types based on climate zone 

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#632]
90.1-2013 Appendix G determines baseline system type based on climate zone: 

![image](https://user-images.githubusercontent.com/10799524/55020475-80829c00-4fbc-11e9-9b0b-5f8f675324a6.png)

Climate zone check should be added here https://github.com/NREL/openstudio-standards/blob/5b7679bb99522db9880bfc64afa842b4533a5967/lib/openstudio-standards/standards/Standards.Model.rb#L614

**Comment by MatthewSteen** [comment]
And #367.

**Comment by mdahlhausen** [comment]
Added in #1363
