### ISSUE TITLE
Support ASHRAE 90.1-2013 Table G3.1.1-1 Baseline Fenestration Percentage based on building type

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#633]
90.1-2013 Baseline vertical fenestration areas should be determined based on building type: 

![image](https://user-images.githubusercontent.com/10799524/55021109-d60b7880-4fbd-11e9-8465-f1d2a9e97297.png)

![image](https://user-images.githubusercontent.com/10799524/55021125-dd328680-4fbd-11e9-9fa6-cd7343961741.png)

**Comment by mdahlhausen** [comment]
Added in #1363
