### ISSUE TITLE
PRM: wrong baseline system assigned when cooling = purchased cooling and heating = natural gas

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#646]
For a large (>150k SF) proposed building with purchased cooling and natural gas heat, the baseline per G3.1.1-3 and G3.1.1.3.2 should be System 7, but the 'create baseline building' measure will create System 8 (https://github.com/NREL/openstudio-standards/blob/5b7679bb99522db9880bfc64afa842b4533a5967/lib/openstudio-standards/standards/Standards.Model.rb#L656)

To reproduce: 
- Create LargeOffice prototype building
- Change datacenter zone systems to gas heat (furnace or HW coil)
- Replace chiller with District Cooling object
- Run baseline measure (tested with 90.1-2013, CZ 5B)

relevant text of debug log: 
[Baseline System 8 debug.txt](https://github.com/NREL/openstudio-standards/files/3059742/Baseline.System.8.debug.txt)

Workaround: replacing NG boiler with DistrictHeating will set baseline system correctly to VAV_reheat.

**Comment by mdahlhausen** [comment]
The create_baseline_building measure is now obsolete with the new PRM workflow: https://github.com/NREL/openstudio-standards/pull/1363
