### ISSUE TITLE
Consider stopping or returning false in space_type_apply_internal_load_schedules  when space_type_properties is empty

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#656]
https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.SpaceType.rb#L468

Currently for unrecognized space types thermostats are being made matching the space type name that do not have heating and cooling setpoints. Measures such as `create_typical_building_from_model` find thermostats with space type name and attempt to hook them up. It results in valid thermostats being removed and invalid thermostats being added. 

I can address this in the measure by validating thermostats or before using or validating `space_type_properties` isn't empty before calling `space_type_apply_internal_load_schedules`, it might be nice to update the method in standard to stop at this point if `space_type_properties` is empty, and maybe even return false. 

It looks like `space_type_apply_internal_loads` does this
https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.SpaceType.rb#L95_L99

**Comment by mdahlhausen** [comment]
Fixed with #995
