### ISSUE TITLE
Consider better linking newly made thermostats to relevant model objects

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#657]
Currently down stream measures that use this method rely on comparing thermostat name to space type names.
https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.SpaceType.rb#L544_L545

I see two approaches to improve this behavior. One is to apply the thermostat to zones that have spaces that use the space type. To be safe maybe this could be a new bool at the end of the method that defaults to false. This way behavior for most users would not change. I do know in some cases like space type and construction set wizard, the model may not have spaces or thermal zones at the time.

The second approach is to lean on additional properties objects by adding reference in the default schedule set made by this method to the preferred thermostat by name and handle. (kind of faking having heating and cooling setpoint in schedule set for space type.). Downstream measures could look at this instead of doing a name comparison. It could handle edge case of thermal zone with spaces of different space types that don't have matching thermostats.

Or, I guess the third approach, would be an OS core change to do just that, but that probably opens can of worms for API, forward translation, and GUI's.

**Comment by DavidGoldwasser** [comment]
@asparke2 do you have preference on doing nothing, option 1, or option2. I can improve name matching in `create_typical_building_from_model` to better handle name clashes, but using name still feels kind of hacky.

**Comment by mdahlhausen** [comment]
@DavidGoldwasser why is linking thermostats to space types more than just the name is necessary? What downstream measures use it? [Here is the relevant section of code](https://github.com/NREL/openstudio-standards/blob/bada5650a676c1bbdd0c68c4c850bb2a0a013ed5/lib/openstudio-standards/standards/Standards.SpaceType.rb#L544) from when you made the issue.

**Comment by DavidGoldwasser** [comment]
I don't believe this is relevant anymore. I believe we now do apply the thermostats to zones that have spaces that use that space type. The confusion on this earlier was that thermostat schedules are not part of the space type default schedule set. They are applied to zones, and zones don't have a direct link to space types except through spaces. This is why space type and construction set wizard didn't do anything with thermostats since it was run on models without spaces or zones. 

I believe for create_typical we are already apply thermostats based on tracking back from zone to spaces and then space types. If we have a zone that has spaces of multiple space types, I'm not sure what we do, but expect we choose the space type has the most spaces in the zone of this space type or look at which space type has the largest fraction of zone's floor area.

Unless someone wants to investigate current behavior for zones with multiple space types (which is edge or corner case) I'm fine closing this.
