### ISSUE TITLE
model_add_heatpump_water_heater Evaporator Air Flow Rate

### ISSUE THREAD

**Issue by agonzalezesteve** [NREL/openstudio-standards#684]
I am using _model_add_heatpump_water_heater_ method in https://github.com/NREL/openstudio-standards/blob/95fe2261b63e5b3db2a230c9712f1dac224e1b67/lib/openstudio-standards/prototypes/common/objects/Prototype.ServiceWaterHeating.rb#L321

but I get the following error in the EnergyPlus simulation
> ** Severe  ** PsyRhoAirFnPbTdbW: RhoAir (Density of Air) is calculated <= 0 [-0.68211].
   **   ~~~   ** pb =[101325.00], tdb=[-790.72], w=[1.0000000E-005].
   **   ~~~   **  Routine=Unknown, Environment=RUN PERIOD 1, at Simulation time=01/01 08:30 - 08:45

Comparing the .idf of my simulation with this EnergyPlus test file 

https://github.com/NREL/EnergyPlus/blob/bee886ab567181a306a8c2e7c678d6a1063b0bb0/testfiles/HeatPumpWaterHeater.idf#L2337

I have noticed that the evaporator flow rate wasn't _autosized_, _model_add_heatpump_water_heater_ method sets the evaporator flow rate to 181.0 ft^3/min.

https://github.com/NREL/openstudio-standards/blob/95fe2261b63e5b3db2a230c9712f1dac224e1b67/lib/openstudio-standards/prototypes/common/objects/Prototype.ServiceWaterHeating.rb#L389

https://github.com/NREL/openstudio-standards/blob/95fe2261b63e5b3db2a230c9712f1dac224e1b67/lib/openstudio-standards/prototypes/common/objects/Prototype.ServiceWaterHeating.rb#L460

https://github.com/NREL/openstudio-standards/blob/95fe2261b63e5b3db2a230c9712f1dac224e1b67/lib/openstudio-standards/prototypes/common/objects/Prototype.ServiceWaterHeating.rb#L538

As the heat pump water heater fan maximum flow rate cannot be _autosized_, I took the _5.035E-5 m^3/s/W_ ratio that EnergyPlus uses to autocalculate the evaporator air flow rate in _WaterHeater:HeatPump:PumpedCondenser_ and _Coil:WaterHeating:AirToWaterHeatPump:Pumped_ objects

https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/group-water-heaters.html#waterheaterheatpumppumpedcondenser

https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/group-heating-and-cooling-coils.html#coilwaterheatingairtowaterheatpumppumped

and the simulation has no errors anymore.

**Comment by mdahlhausen** [comment]
Fixed with #1420
