### ISSUE TITLE
Issue with Internal Variables and Automated Baseline Generation

### ISSUE THREAD

**Issue by lymereJ** [NREL/openstudio-standards#688]
When using the `model_create_prm_baseline_building` method on a model with `EnergyManagementSystem:InternalVariable` objects, the sizing run failed because objects related to the `EnergyManagementSystem:InternalVariable` (in that case a `Controller:OutdoorAir` object) was removed from the model by the measure.

**Comment by mdahlhausen** [comment]
To further specify this problem - the idea is that when generating the baseline HVAC system, the model doesn't remove EnergyManagementSystem objects related to the proposed HVAC.

This is subset of a larger problem of orphaned EnergyManagementSystem objects.  Perhaps it makes sense to delete all EnergyManagementSystem objects as part of the method?

**Comment by mdahlhausen** [comment]
@lymereJ I'm trying to recreate this with the 'Create DOE Prototype Building' measure in combination with the 'Create Baseline Building' measure, but it seems that the single zone controls aren't being applied in the .osm files in many instances where they exist in the .idf files.  Can you recommend a template, building type, and climate zone combination that exhibits this error?

**Comment by lymereJ** [comment]
I was also using these two measures, here's an example: small hotel, 90.1-2004, and 5B.

**Comment by mdahlhausen** [comment]
Fixed with https://github.com/NREL/openstudio-standards/pull/716
