### ISSUE TITLE
Directory tree and filenames result in paths that are too long for Windows

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#697]
I've had that issue just checking out openstudio-standards recently (to `C:\Users\julien\Software\Others\openstudio-standards` where I usually clone it). That was easy to resolve using the `LongPathsEnabled` regkey trick on Windows 10, but it won't work for MSVC 2013. (It also won't work for Windows 8.1 or 7 for that matter).

We cannot build OpenStudio as a result right now, cf https://github.com/NREL/OpenStudio/pull/3677#issuecomment-532235489

The worst is this one is 157 chars already: `/lib/openstudio-standards/standards/ashrae_90_1/doe_ref_1980_2004/comstock_doe_ref_1980_2004/data/comstock_doe_ref_1980_2004.refrigeration_system_lineup.json` 

If I were to clone OpenStudio to `C:\OpenStudio`, and build in `C:\OpenStudio\build` (as is customary/per wiki notes), I would be already dangerously close to the `MAX_PATH` limitation.

I would suggest keeping the limitation in mind and avoid having internal paths that are so long.

**Comment by mdahlhausen** [comment]
@asparke2 this is fixed, right?

**Comment by asparke2** [comment]
Fixed by #706
