### ISSUE TITLE
Add evaportive fluid cooler methods and efficiency data

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#698]
The 90.1 highrise apartment models use an evaportive fluid cooler single speed object to provide cooling to the heat pump loop.  Currently, there are no data or methods to apply 90.1 efficiency standards to fluid coolers.

[This branch](https://github.com/NREL/openstudio-standards/tree/hvac) adds methods to apply efficiency standards for non-evaportively cooled fluid cooler only.

Scope of work:
- add evaportively cooled fluid-cooler efficiency data to the heat_rejection tab of the 90.1 spreadsheet (and other templates)
- add or modify methods to adjust EvaportiveFluidCoolerSingleSpeed and EvaportiveFluidCoolerTwoSpeed efficiency to the data
- re-generate highrise apartment prototype regression models and performance results

**Comment by jiangithub** [comment]
This fluid cooler would be a closed circuit cooling towers. We should be using the efficiency for propeller or axial fan CCCT from 6.8.1-7 but missed it. The efficiency requirement was first introduced in 2010 and efficiency improved in 2016. @mdahlhausen If you can work on it, that's great. It'll take a while to bring this to the top of our to do list.

**Comment by lymereJ** [comment]
It looks like the data was added, and the method updated.
