### ISSUE TITLE
Space type Color not found

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-standards#704]
I'm running PAT project with comstock_fixes branch and mixed use Midrise and stand alone retail, I. I noticed colors were not found for any of the space types. Possible this broke a while ago but I think it was good in 2.8.0, at least for some building types. 

```"[22:34:57.633052 WARN] Could not find color for 90.1-2013 MidriseApartment Apartment```

**Comment by mdahlhausen** [comment]
Fixed with https://github.com/NREL/openstudio-standards/pull/732
