### ISSUE TITLE
assign building stories

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#72]
The standards generate buildings that lack building stories.  
Since the OSLib_HVAC libraries rely on building story assignments to create air loops, any measure using the OSLib_HVAC libraries (including AEDG measures) won't generate air loops when run.

It seems like you've already made a method to add building stories in the ```Prototype.Model.rb``` code:
````ruby
def assign_building_story(building_type, building_vintage, climate_zone, building_story_map)
    building_story_map.each do |building_story_name, space_names|
    ...
```
... but haven't yet made the ```building_story_map``` objects as part of each ```Prototype.<building_type>.rb``` file.  This seems like this would be pretty quick.  Was there a reason why this wasn't working?

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/commit/0eaf0d5fb82d57097bb8f0270fa7425af13318df

**Comment by DavidGoldwasser** [comment]
@asparke2 this code seemed to get lost again.
