### ISSUE TITLE
non-integrated air-side economizers not being specified properly

### ISSUE THREAD

**Issue by lincolnharmer** [NREL/openstudio-standards#73]
The Lockout Type for the Controller:OutdoorAir object is being set to "NoLockout" for non-integrated economizers [here](https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb#L1025). This means that when the unit is in heating mode the outdoor air damper is not at its minimum position like it should be for correct economizer control. This results in excessive heating energy use. Setting this line to "LockoutWithHeating" should fix the problem.

**Comment by lincolnharmer** [comment]
Just made a commit to the [fix non integrated airside economizers branch](https://github.com/NREL/openstudio-standards/tree/fix-non-integrated-air-side-economizer) to fix this

**Comment by asparke2** [comment]
I'll talk to the PNNL folks about this one.
