### ISSUE TITLE
Fix the `DummrySmrDsn` typo in the ashrae_90_1 schedules to be 'DummySmrDsn' like all of the other schedules

### ISSUE THREAD

**Issue by chriswmackey** [NREL/openstudio-standards#736]
There are a couple of typos in the [ashrae_90_1 schedules](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/ashrae_90_1/data/ashrae_90_1.schedules.json) file, which you can find just by doing cntrl+F for `DummrySmrDsn`. You can see one of them here:
![image](https://user-images.githubusercontent.com/5567574/69460249-a7f35980-0d41-11ea-8a27-8df74c69d2dc.png)

I imagine that the place to fix this is within the google sheets.

As a side question, what is the purpose of the `DummySmrDsn`?  It feels a bit like a patch that was made to get something else to work. Is it something that is planned to stay within the standards gem data?

**Comment by mdahlhausen** [comment]
Fixed with #763
