### ISSUE TITLE
Fix the schedules in the ashrae_90_1 schedules that don't have 1 or 24 values

### ISSUE THREAD

**Issue by chriswmackey** [NREL/openstudio-standards#737]
As I was writing some functions to clean up the standards gem data for my own purposes, I realized that there are a couple of schedules that seem to have 2 values and so they don't conform to the standard that seems to be used throughout the JSON of only having a single constant value or 24 values for each hour. This seems to be a bug or typo that probably originates in the standards google sheet.  The two schedules that have this issue area:
"Courthouse COURTROOM_OCC_SCH"
"StripMall Bldg Light"

**Comment by mdahlhausen** [comment]
Fixed by #762
