### ISSUE TITLE
plant_loop_cooling_fuels method with HeatExchanger:FluidToFluid in the Supply Side

### ISSUE THREAD

**Issue by agonzalezesteve** [NREL/openstudio-standards#754]
The OpenStudio standards library deals with heating loops with HeatExchanger:FluidToFluid in the supply side

https://github.com/NREL/openstudio-standards/blob/12372aed81d74470433aa99738ac14ca31ed36e0/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb#L67

but the same cannot be said for cooling.

https://github.com/NREL/openstudio-standards/blob/12372aed81d74470433aa99738ac14ca31ed36e0/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb#L88

**Comment by mdahlhausen** [comment]
Fixed with #1437
