### ISSUE TITLE
Don't apply economizers to unitary systems

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#756]
Unitary HVAC systems generally don't have outdoor air, so they can't have an economizer.

The `air_loop_hvac_economizer_required?` method doesn't check if an air loop is a unitary system, and so residential HVAC system types in openstudio-standards get thrown this error:
`OpenStudio.logFree(OpenStudio::Error, 'openstudio.prototype.Model', "#{air_loop.name} is required to have an economizer, but it has no OA system.")`

The fix is to add a check in the `air_loop_hvac_economizer_required?` method to skip unitary system types.

**Comment by jiangithub** [comment]
Single-zone systems, such as PSZ-AC and PSZ-HP are unitary systems. They serve commercial spaces and may have air economizer. We should not use "Unitary" as a keyword to disable economizers.

**Comment by mdahlhausen** [comment]
@jiangithub many of the unitary system types in openstudio-standards don't have outdoor air terminals.  I'll refactor the code to exclude air loops without outdoor air, rather than if it is a unitary system.

**Comment by mdahlhausen** [comment]
@jiangithub many of the unitary system types in openstudio-standards don't have outdoor air terminals.  I'll refactor the code to exclude air loops without outdoor air, rather than if it is a unitary system.
