### ISSUE TITLE
Economizers aren't being enabled for PSZ-AC

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#77]
Need to set the economizer type in Standards.AirLoopHVAC. The economizer type is determined but never set (the temperature/enthalpy limits are).

Around https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb#L1231

Add

    # Set the Economizer Type
     oa_control.setEconomizerControlType(economizer_type)

    

I'll do a PR once I'm done working on my current project (for which I've modified a lot of code to suit my own needs)

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/pull/95
