### ISSUE TITLE
Change iddObjectType for Coils

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#78]
https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.CoilCoolingDXSingleSpeed.rb#L45

https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.CoilCoolingDXTwoSpeed.rb#L205

These should be appended "OS:" because it doesn't work right now.

I'll do a PR asap.

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/pull/95
