### ISSUE TITLE
PRM: Hot Water Loop Ends up with a SPM Scheduled instead of OA Reset

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-standards#79]
G3.1.3.4 Hot-Water Supply Temperature Reset (Systems
1, 5, and 7). Hot-water supply temperature shall be reset
based on outdoor dry-bulb temperature using the following
schedule: 180°F at 20°F and below, 150°F at 50°F and above,
and ramped linearly between 180°F and 150°F at temperatures
between 20°F and 50°F.

**Comment by MatthewSteen** [comment]
The code Incorrectly references the HVAC section of the code [here](https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.PlantLoop.rb#L321) instead of following Appendix G.

**Comment by MatthewSteen** [comment]
This may get tricky if the proposed model has a heating plant loop for SHW, which can have other types of SPMs. See [EnergyPlus #5613](https://github.com/NREL/EnergyPlus/issues/5613).

**Comment by jmarrec** [comment]
That's not the problem actually.

Improper test: missing ".is_initialized"

https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.PlantLoop.rb#L360

Couple of lines later (368), should be design_temp_c = sizing_plant.designLoopExitTemperature

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/commit/0eaf0d5fb82d57097bb8f0270fa7425af13318df
