### ISSUE TITLE
add utility costs to DOE reference models

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/openstudio-standards#829]
Feature request to add the rates/tariffs to the the `Create DOE Prototype Building` measure. The UtilityCost:* objects are in the DOE reference building IDFs but not currently in the measure.

**Comment by lymereJ** [comment]
Which prototypes IDFs are you referring to? The [Commercial Prototype Buildings](https://www.energycodes.gov/development/commercial/prototype_models)?

**Comment by MatthewSteen** [comment]
@lymereJ sorry, meant reference building models.

**Comment by mdahlhausen** [comment]
Not going to add these - we are no longer trying to replicate the DOE prototypes exactly in OpenStudio.
