### ISSUE TITLE
Running errors with ASHRAEMediumOfficeDetailed.osm

### ISSUE THREAD

**Issue by Cyy-fresh1994** [NREL/openstudio-standards#832]
I input the ASHRAEMediumOfficeDetailed.osm into OpenStudio and tried to run it. However, it gives fatal errors as follows:

Initializing workflow.
Processing OpenStudio Measures.
Translating the OpenStudio Model to EnergyPlus.
Processing EnergyPlus Measures.
Starting Simulation.
EnergyPlus Starting
EnergyPlus, Version 9.2.0-921312fa1d, YMD=2020.06.15 21:14
**FATAL:Errors occurred on processing input file. Preceding condition(s) cause termination.
EnergyPlus Run Time=00hr 00min  0.51sec
Program terminated: EnergyPlus Terminated--Error(s) Detected.
Failed.

**Comment by mdahlhausen** [comment]
There is insufficient information to determine the cause of the error.  It is most like a user input error, but could also be openstudio, energyplus, or openstudio-standards.  Please post more detail on the unmet hours forum for further support.
