### ISSUE TITLE
PRM: System 6 not created in add_performance_rating_method_baseline_system

### ISSUE THREAD

**Issue by eringold** [NREL/openstudio-standards#84]
System 6's are currently not created: https://github.com/NREL/openstudio-standards/blob/7d32e8ed3de795c6ebd9e2b2730fc4ec5a8fdaff/openstudio-standards/lib/openstudio-standards/standards/Standards.Model.rb#L771

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/commit/0eaf0d5fb82d57097bb8f0270fa7425af13318df
