### ISSUE TITLE
PRM: creates SPM Scheduled instead of OA Reset for chilled water loops 

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/openstudio-standards#85]
Applies to 2007, 2010, and 2013. The code incorrectly defaults to `reset_required = false` in [this method](https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.PlantLoop.rb#L321). The code should instead apply OA reset control to both CHW and HW loops (#79) by default. 

>G3.1.3.9 Chilled-Water Supply Temperature Reset
(Systems 7, 8, 11, 12, and 13). Chilled-water supply temperature shall be reset based on outdoor dry-bulb temperatureusing the following schedule: 44°F at 80°F and above, 54°F at60°F and below, and ramped linearly between 44°F and 54°Fat temperatures between 80°F and 60°F.

**Comment by asparke2** [comment]
The standards.is_foo_required methods apply the logic from the body of 90.1, not Appendix G.  In this case, this method is doing the logic from 6.5.4.2 Chilled and Hot-Water Temperature Reset Controls.

The logic to apply the Appendix G controls lives [here](https://github.com/NREL/openstudio-standards/blob/baseline_automation_90.1_fixes/openstudio-standards/lib/openstudio-standards/standards/Standards.PlantLoop.rb#L136).
