### ISSUE TITLE
PRM: does not create district heating or cooling

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/openstudio-standards#86]
Applies to 2007, 2010, and 2013. There should probably be a method in [Standards.PlantLoop](https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards/lib/openstudio-standards/standards/Standards.PlantLoop.rb) to accout for purchased heat and/or chilled water.

>G3.1.1.1 Purchased Heat. For systems using purchased
hot water or steam, the heating source shall be modeled as
purchased hot water or steam in both the proposed and baseline building designs. Hot water or steam costs shall be basedon actual utility rates, and on-site boilers, electric heat, andfurnaces shall not be modeled in the baseline building design.G3.1.1.2 Purchased Chilled Water. For systems usingpurchased chilled water, the cooling source shall be modeledas purchased chilled water in both the proposed and baselinebuilding designs. Purchased chilled water costs shall be basedon actual utility rates, and on-site chillers and direct expansion equipment shall not be modeled in the baseline buildingdesign.

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/openstudio-standards/commit/0eaf0d5fb82d57097bb8f0270fa7425af13318df
