### ISSUE TITLE
suggestion: add labels for specific standards

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/openstudio-standards#88]

**Comment by jmarrec** [comment]
can you elaborate a little?

**Comment by MatthewSteen** [comment]
Technically GitHub labels. I was thinking it will probably be helpful in the future to tag issues with labels for specific standards because an issue might not apply to all vintages. For example, one for 90.1-2004, etc.

**Comment by asparke2** [comment]
Good idea.  Done.
