### ISSUE TITLE
Remove unused JSON files

### ISSUE THREAD

**Issue by asparke2** [NREL/openstudio-standards#925]
There are old, unused JSON files still in the data directory that need to be removed to avoid confusing people.  See screenshot below.  All data being used by the gem should be found next to the standards in the data/ subdirectories.

![image](https://user-images.githubusercontent.com/2009290/93814690-1d55e200-fc12-11ea-9e50-8a0a5b2d6a54.png)

**Comment by mdahlhausen** [comment]
@asparke2 you must have not seen #924 ?
