### ISSUE TITLE
WWR differences in EnergyPlus and OpenStudio SmallOffice models

### ISSUE THREAD

**Issue by asparke2** [NREL/openstudio-standards#94]
WWR differences in EnergyPlus and OpenStudio SmallOffice model due to osm classifying door as glassdoor and IDF classifying as opaque.

From [UnmetHours](https://unmethours.com/question/18959/difference-in-window-area-between-energyplus-and-openstudio-doe-prototype-buildings/).

**Comment by lymereJ** [comment]
This issue was addressed.
