### ISSUE TITLE
Revise fenestration categories

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-standards#958]
There was a change between 90.1-2010 with windows defined as curtainwall/storefront switching to fixed/operable.
The default 'all other' values listed in the spreadsheet are for entrance doors.
Need to update the U-value table for 90.1-2013 and doublecheck for all windows to make sure it aligns with 90.1.

**Comment by asparke2** [comment]
Here's my summary of reviewing this:

![image](https://user-images.githubusercontent.com/2009290/96613723-86d21a80-12bc-11eb-9e17-c33b86197898.png)

Basically 90.1-2013 onward uses different categorization/enumeration for windows.  We should discuss whether or not it makes sense to change (expand) the enumerations, or change the mapping from earlier to later versions of 90.1.  The challenge with changing enumerations is that previously-generated models could have enumerations that are no longer valid, which is an important consideration for users using openstudio-standards to create 90.1-2013 baseline buildings for design projects as part of incentive programs.

**Comment by mdahlhausen** [comment]
Fixed with #1795
