### ISSUE TITLE
Autogenerated multi-space occupancy schedule rounding issue

### ISSUE THREAD

**Issue by asparke2** [NREL/openstudio-standards#962]
Calling the method `spaces_get_occupancy_schedule()` with an input `occupied_percentage_threshold` that is equal to the occupancy schedule fractional values can lead to unexpected outcomes due to rounding error.  This rounding is introduced when the occupant density is multiplied by the fractional value.  In the example image below, the models on either side use the same exact occupancy schedules, but due to the rounding differences, the final schedules are significantly different.

![image](https://user-images.githubusercontent.com/2009290/97356356-c4efb100-185d-11eb-83af-87a76192cd32.png)

The proposed solution is to round the calculated occupancy fraction for each hour to 3 decimal places before comparing against the `occupied_percentage_threshold`.

**Comment by mdahlhausen** [comment]
@phylroy @ckirney this causes some changes in the necb workflow, causing regression errors.  Please review and either override the method or update the regression models.

**Comment by mdahlhausen** [comment]
@asparke2 NRCAN will update the regression tests and then we can merge.

**Comment by phylroy** [comment]
@mdahlhausen I'll fix the regression file next week.

**Comment by ckirney** [comment]
Tests updated.  Please see pull request #972.
