### ISSUE TITLE
"Create Baseline Building" measure warning "zero allowable fan bhp, probably due to zero design air flow cfm"

### ISSUE THREAD

**Issue by agonzalezesteve** [NREL/openstudio-standards#987]
Using the "Create Baseline Building" measure we get the following warning:

`WARN  AirLoopHVAC Thermal Zone: Sala Juntas PSZ-HP has zero allowable fan bhp, probably due to zero design air flow cfm'.`

So I think it's because in line

https://github.com/NREL/openstudio-standards/blob/4f6fc53347e8fbbc57d76d37dfe0c2a9b8ab475f/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb#L475

"fan" object should be used instead of "comp".

**Comment by mdahlhausen** [comment]
#1061
