### ISSUE TITLE
LPD of Multifamily

### ISSUE THREAD

**Issue by asparke2** [NREL/openstudio-standards#99]
From @jmarrec:

> All programs for Multifamily buildings (LEED MFHR, NYSERDA MPP) that I've modeled for determine the LPD for apartment by looking up the Building Area LPD for "Multifamily". So 0.7 W/ft^2 for ASHRAE 90.1-2007 and 0.6 W/ft^2 for ASHRAE 90.1-2010 (TABLE 9.5.1)

Need to square this with the DOE Prototype Buildings before making a change.

**Comment by mirosenberg** [comment]
90.1 and most codes exempt the lighting in dwelling units. Therefore the lpd allowances do not apply. The assumptions in the prototype multifamily dwelling units are based on the Building America program.
